//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.vehicle;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import com.cts.product.rental.dto.reservation.CarClass;


/**
 * This element contains a vehicle content.
 * 
 * <p>Java class for VehicleContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleContent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.ehi.gbo.rental.dto.vehicle/}CommonVehicleContent"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="makeModelOrSimilarText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="twoOrFourDoorText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="smallLuggageCapacity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="largeLuggageCapacity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="luggageCapacity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="peopleCapacity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="specialityVehicle" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="termsAndConditionsRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="category" type="{http://com.ehi.gbo.rental.dto.vehicle/}VehicleCategory"/&gt;
 *         &lt;element name="features" type="{http://com.ehi.gbo.rental.dto.vehicle/}VehicleFeatureContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="featuresShort" type="{http://com.ehi.gbo.rental.dto.vehicle/}VehicleFeatureContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="filters" type="{http://com.ehi.gbo.rental.dto.vehicle/}Filter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="mileageInfo" type="{http://com.ehi.gbo.rental.dto.vehicle/}MileageInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleContent", propOrder = {
    "makeModelOrSimilarText",
    "twoOrFourDoorText",
    "smallLuggageCapacity",
    "largeLuggageCapacity",
    "luggageCapacity",
    "peopleCapacity",
    "specialityVehicle",
    "termsAndConditionsRequired",
    "category",
    "features",
    "featuresShorts",
    "filters",
    "mileageInfo"
})
@XmlSeeAlso({
    CarClass.class
})
public class VehicleContent
    extends CommonVehicleContent
    implements Serializable
{

    @XmlElement(required = true)
    protected String makeModelOrSimilarText;
    @XmlElement(required = true)
    protected String twoOrFourDoorText;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer smallLuggageCapacity;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer largeLuggageCapacity;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer luggageCapacity;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer peopleCapacity;
    protected boolean specialityVehicle;
    protected boolean termsAndConditionsRequired;
    @XmlElement(required = true)
    protected VehicleCategory category;
    protected List<VehicleFeatureContent> features;
    @XmlElement(name = "featuresShort")
    protected List<VehicleFeatureContent> featuresShorts;
    protected List<Filter> filters;
    @XmlElement(required = true)
    protected MileageInfo mileageInfo;

    /**
     * Gets the value of the makeModelOrSimilarText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakeModelOrSimilarText() {
        return makeModelOrSimilarText;
    }

    /**
     * Sets the value of the makeModelOrSimilarText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakeModelOrSimilarText(String value) {
        this.makeModelOrSimilarText = value;
    }

    /**
     * Gets the value of the twoOrFourDoorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwoOrFourDoorText() {
        return twoOrFourDoorText;
    }

    /**
     * Sets the value of the twoOrFourDoorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwoOrFourDoorText(String value) {
        this.twoOrFourDoorText = value;
    }

    /**
     * Gets the value of the smallLuggageCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSmallLuggageCapacity() {
        return smallLuggageCapacity;
    }

    /**
     * Sets the value of the smallLuggageCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSmallLuggageCapacity(Integer value) {
        this.smallLuggageCapacity = value;
    }

    /**
     * Gets the value of the largeLuggageCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLargeLuggageCapacity() {
        return largeLuggageCapacity;
    }

    /**
     * Sets the value of the largeLuggageCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLargeLuggageCapacity(Integer value) {
        this.largeLuggageCapacity = value;
    }

    /**
     * Gets the value of the luggageCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLuggageCapacity() {
        return luggageCapacity;
    }

    /**
     * Sets the value of the luggageCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLuggageCapacity(Integer value) {
        this.luggageCapacity = value;
    }

    /**
     * Gets the value of the peopleCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPeopleCapacity() {
        return peopleCapacity;
    }

    /**
     * Sets the value of the peopleCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPeopleCapacity(Integer value) {
        this.peopleCapacity = value;
    }

    /**
     * Gets the value of the specialityVehicle property.
     * 
     */
    public boolean isSpecialityVehicle() {
        return specialityVehicle;
    }

    /**
     * Sets the value of the specialityVehicle property.
     * 
     */
    public void setSpecialityVehicle(boolean value) {
        this.specialityVehicle = value;
    }

    /**
     * Gets the value of the termsAndConditionsRequired property.
     * 
     */
    public boolean isTermsAndConditionsRequired() {
        return termsAndConditionsRequired;
    }

    /**
     * Sets the value of the termsAndConditionsRequired property.
     * 
     */
    public void setTermsAndConditionsRequired(boolean value) {
        this.termsAndConditionsRequired = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleCategory }
     *     
     */
    public VehicleCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleCategory }
     *     
     */
    public void setCategory(VehicleCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the features property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleFeatureContent }
     * 
     * 
     */
    public List<VehicleFeatureContent> getFeatures() {
        if (features == null) {
            features = new ArrayList<VehicleFeatureContent>();
        }
        return this.features;
    }

    /**
     * Gets the value of the featuresShorts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featuresShorts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeaturesShorts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleFeatureContent }
     * 
     * 
     */
    public List<VehicleFeatureContent> getFeaturesShorts() {
        if (featuresShorts == null) {
            featuresShorts = new ArrayList<VehicleFeatureContent>();
        }
        return this.featuresShorts;
    }

    /**
     * Gets the value of the filters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Filter }
     * 
     * 
     */
    public List<Filter> getFilters() {
        if (filters == null) {
            filters = new ArrayList<Filter>();
        }
        return this.filters;
    }

    /**
     * Gets the value of the mileageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MileageInfo }
     *     
     */
    public MileageInfo getMileageInfo() {
        return mileageInfo;
    }

    /**
     * Sets the value of the mileageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MileageInfo }
     *     
     */
    public void setMileageInfo(MileageInfo value) {
        this.mileageInfo = value;
    }

}
