//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 07:18:08 PM IST 
//


package com.cts.product.profile.dto.messages;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardSubmissionKeyResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardSubmissionKeyResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.ehi.gbo.profile.dto.messages/}Response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cardSubmissionKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paymentContextData" type="{http://com.ehi.gbo.profile.dto.messages/}PaymentContextData"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardSubmissionKeyResponse", propOrder = {
    "cardSubmissionKey",
    "paymentContextData"
})
public class CardSubmissionKeyResponse
    extends Response
    implements Serializable
{

    @XmlElement(required = true)
    protected String cardSubmissionKey;
    @XmlElement(required = true)
    protected PaymentContextData paymentContextData;

    /**
     * Gets the value of the cardSubmissionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardSubmissionKey() {
        return cardSubmissionKey;
    }

    /**
     * Sets the value of the cardSubmissionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardSubmissionKey(String value) {
        this.cardSubmissionKey = value;
    }

    /**
     * Gets the value of the paymentContextData property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentContextData }
     *     
     */
    public PaymentContextData getPaymentContextData() {
        return paymentContextData;
    }

    /**
     * Sets the value of the paymentContextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentContextData }
     *     
     */
    public void setPaymentContextData(PaymentContextData value) {
        this.paymentContextData = value;
    }

}
