//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 07:18:08 PM IST 
//


package com.cts.product.profile.dto.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.cts.product.profile.dto.profiles.PartnerRewardProgram;


/**
 * <p>The Partner Rewards Program Response List</p>
 *             
 * 
 * <p>Java class for PartnerRewardsProgramsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerRewardsProgramsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.ehi.gbo.profile.dto.messages/}Response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="partnerRewardsPrograms" type="{http://com.ehi.gbo.profile.dto.profiles/}PartnerRewardProgram" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerRewardsProgramsResponse", propOrder = {
    "partnerRewardsPrograms"
})
public class PartnerRewardsProgramsResponse
    extends Response
    implements Serializable
{

    @XmlElement(required = true)
    protected List<PartnerRewardProgram> partnerRewardsPrograms;

    /**
     * Gets the value of the partnerRewardsPrograms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partnerRewardsPrograms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartnerRewardsPrograms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartnerRewardProgram }
     * 
     * 
     */
    public List<PartnerRewardProgram> getPartnerRewardsPrograms() {
        if (partnerRewardsPrograms == null) {
            partnerRewardsPrograms = new ArrayList<PartnerRewardProgram>();
        }
        return this.partnerRewardsPrograms;
    }

}
