//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.cts.product.rental.dto.common.LocationPair;


/**
 * <p>Java class for CarClassesAvailabilityRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarClassesAvailabilityRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.cts.product.rental.dto.messages/}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}pickupTime"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}returnTime"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}contractNumber"/&gt;
 *         &lt;element name="locationPairs" type="{http://com.cts.product.rental.dto.common/}LocationPair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="carClasses" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarClassesAvailabilityRequest", propOrder = {
    "pickupTime",
    "returnTime",
    "contractNumber",
    "locationPairs",
    "carClasses"
})
public class CarClassesAvailabilityRequest
    extends Request
    implements Serializable
{

    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String pickupTime;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String returnTime;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String contractNumber;
    protected List<LocationPair> locationPairs;
    protected List<String> carClasses;

    /**
     * Gets the value of the pickupTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupTime() {
        return pickupTime;
    }

    /**
     * Sets the value of the pickupTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupTime(String value) {
        this.pickupTime = value;
    }

    /**
     * Gets the value of the returnTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnTime() {
        return returnTime;
    }

    /**
     * Sets the value of the returnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnTime(String value) {
        this.returnTime = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the locationPairs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationPairs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationPairs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationPair }
     * 
     * 
     */
    public List<LocationPair> getLocationPairs() {
        if (locationPairs == null) {
            locationPairs = new ArrayList<LocationPair>();
        }
        return this.locationPairs;
    }

    /**
     * Gets the value of the carClasses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carClasses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarClasses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCarClasses() {
        if (carClasses == null) {
            carClasses = new ArrayList<String>();
        }
        return this.carClasses;
    }

}
