//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.util.HashMap;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.ehi.gbo.rental.dto.messages/}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tokenInput" type="{http://com.ehi.gbo.rental.dto.messages/}TokenMapModeller" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptRequest", propOrder = {
    "tokenInput"
})
public class EncryptRequest
    extends Request
    implements Serializable
{

    @XmlElement(type = TokenMapModeller.class)
    protected HashMap<String, String> tokenInput;

    /**
     * Gets the value of the tokenInput property.
     * 
     * @return
     *     possible object is
     *     {@link TokenMapModeller }
     *     
     */
    public HashMap<String, String> getTokenInput() {
        return tokenInput;
    }

    /**
     * Sets the value of the tokenInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenMapModeller }
     *     
     */
    public void setTokenInput(HashMap<String, String> value) {
        this.tokenInput = value;
    }

}
