//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.cts.product.rental.dto.pricing.PartnerRewardProgram;


/**
 * <p>The response containing the partner reward programs
 *                 configured for a brand and a country .</p> 
 * 
 * <p>Java class for GetPartnerRewardProgramsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetPartnerRewardProgramsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.ehi.gbo.rental.dto.messages/}Response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PartnerRewardPrograms" type="{http://com.ehi.gbo.rental.dto.pricing/}PartnerRewardProgram" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetPartnerRewardProgramsResponse", propOrder = {
    "partnerRewardPrograms"
})
public class GetPartnerRewardProgramsResponse
    extends Response
    implements Serializable
{

    @XmlElement(name = "PartnerRewardPrograms")
    protected List<PartnerRewardProgram> partnerRewardPrograms;

    /**
     * Gets the value of the partnerRewardPrograms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partnerRewardPrograms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartnerRewardPrograms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartnerRewardProgram }
     * 
     * 
     */
    public List<PartnerRewardProgram> getPartnerRewardPrograms() {
        if (partnerRewardPrograms == null) {
            partnerRewardPrograms = new ArrayList<PartnerRewardProgram>();
        }
        return this.partnerRewardPrograms;
    }

}
