//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.cts.product.rental.dto.common.enums.BookingAgent;
import com.cts.product.rental.dto.common.enums.TravelPurposeEnum;
import com.cts.product.rental.dto.reservation.AdditionalInformationData;


/**
 * <p>Java class for InitiateReservationRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitiateReservationRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.cts.product.rental.dto.messages/}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}pickupLocationId"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}returnLocationId"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}pickupTime"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}returnTime"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}renterAge"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}contractNumber"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}travelPurpose"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}showRedemptionRateToClient"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}viewCurrencyCode"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}iataNumber"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}cashInClubNumber"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}authPin"/&gt;
 *         &lt;element name="additionalInformation" type="{http://com.cts.product.rental.dto.reservation/}AdditionalInformationData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}partnerRewardProgramCode"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}partnerRewardProgramMemberId"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}lastName"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}membershipId"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}loyaltyBrand"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.pricing/}productCode"/&gt;
 *         &lt;element name="enableNorthAmericanPrepayRates" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="coupons" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="redemptionDayCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="bookingAgent" type="{http://com.cts.product.rental.dto.common.enums/}BookingAgent"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitiateReservationRequest", propOrder = {
    "pickupLocationId",
    "returnLocationId",
    "pickupTime",
    "returnTime",
    "renterAge",
    "contractNumber",
    "travelPurpose",
    "showRedemptionRateToClient",
    "viewCurrencyCode",
    "iataNumber",
    "cashInClubNumber",
    "authPin",
    "additionalInformation",
    "partnerRewardProgramCode",
    "partnerRewardProgramMemberId",
    "lastName",
    "membershipId",
    "loyaltyBrand",
    "productCode",
    "enableNorthAmericanPrepayRates",
    "coupons",
    "redemptionDayCount",
    "bookingAgent"
})
public class InitiateReservationRequest
    extends Request
    implements Serializable
{

    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String pickupLocationId;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String returnLocationId;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String pickupTime;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String returnTime;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Integer.class, nillable = true)
    protected Integer renterAge;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String contractNumber;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    @XmlSchemaType(name = "string")
    protected TravelPurposeEnum travelPurpose;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/")
    protected boolean showRedemptionRateToClient;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String viewCurrencyCode;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String iataNumber;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String cashInClubNumber;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String authPin;
    protected List<AdditionalInformationData> additionalInformation;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String partnerRewardProgramCode;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String partnerRewardProgramMemberId;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String lastName;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String membershipId;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String loyaltyBrand;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.pricing/", required = true)
    protected String productCode;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean enableNorthAmericanPrepayRates;
    protected List<String> coupons;
    protected int redemptionDayCount;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BookingAgent bookingAgent;

    /**
     * Gets the value of the pickupLocationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupLocationId() {
        return pickupLocationId;
    }

    /**
     * Sets the value of the pickupLocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupLocationId(String value) {
        this.pickupLocationId = value;
    }

    /**
     * Gets the value of the returnLocationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnLocationId() {
        return returnLocationId;
    }

    /**
     * Sets the value of the returnLocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnLocationId(String value) {
        this.returnLocationId = value;
    }

    /**
     * Gets the value of the pickupTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupTime() {
        return pickupTime;
    }

    /**
     * Sets the value of the pickupTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupTime(String value) {
        this.pickupTime = value;
    }

    /**
     * Gets the value of the returnTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnTime() {
        return returnTime;
    }

    /**
     * Sets the value of the returnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnTime(String value) {
        this.returnTime = value;
    }

    /**
     * Gets the value of the renterAge property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRenterAge() {
        return renterAge;
    }

    /**
     * Sets the value of the renterAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRenterAge(Integer value) {
        this.renterAge = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the travelPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link TravelPurposeEnum }
     *     
     */
    public TravelPurposeEnum getTravelPurpose() {
        return travelPurpose;
    }

    /**
     * Sets the value of the travelPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TravelPurposeEnum }
     *     
     */
    public void setTravelPurpose(TravelPurposeEnum value) {
        this.travelPurpose = value;
    }

    /**
     * Gets the value of the showRedemptionRateToClient property.
     * 
     */
    public boolean isShowRedemptionRateToClient() {
        return showRedemptionRateToClient;
    }

    /**
     * Sets the value of the showRedemptionRateToClient property.
     * 
     */
    public void setShowRedemptionRateToClient(boolean value) {
        this.showRedemptionRateToClient = value;
    }

    /**
     * Gets the value of the viewCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewCurrencyCode() {
        return viewCurrencyCode;
    }

    /**
     * Sets the value of the viewCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewCurrencyCode(String value) {
        this.viewCurrencyCode = value;
    }

    /**
     * Gets the value of the iataNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIataNumber() {
        return iataNumber;
    }

    /**
     * Sets the value of the iataNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIataNumber(String value) {
        this.iataNumber = value;
    }

    /**
     * Gets the value of the cashInClubNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashInClubNumber() {
        return cashInClubNumber;
    }

    /**
     * Sets the value of the cashInClubNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashInClubNumber(String value) {
        this.cashInClubNumber = value;
    }

    /**
     * Gets the value of the authPin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthPin() {
        return authPin;
    }

    /**
     * Sets the value of the authPin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthPin(String value) {
        this.authPin = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationData }
     * 
     * 
     */
    public List<AdditionalInformationData> getAdditionalInformation() {
        if (additionalInformation == null) {
            additionalInformation = new ArrayList<AdditionalInformationData>();
        }
        return this.additionalInformation;
    }

    /**
     * Gets the value of the partnerRewardProgramCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerRewardProgramCode() {
        return partnerRewardProgramCode;
    }

    /**
     * Sets the value of the partnerRewardProgramCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerRewardProgramCode(String value) {
        this.partnerRewardProgramCode = value;
    }

    /**
     * Gets the value of the partnerRewardProgramMemberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerRewardProgramMemberId() {
        return partnerRewardProgramMemberId;
    }

    /**
     * Sets the value of the partnerRewardProgramMemberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerRewardProgramMemberId(String value) {
        this.partnerRewardProgramMemberId = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the membershipId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembershipId() {
        return membershipId;
    }

    /**
     * Sets the value of the membershipId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembershipId(String value) {
        this.membershipId = value;
    }

    /**
     * Gets the value of the loyaltyBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoyaltyBrand() {
        return loyaltyBrand;
    }

    /**
     * Sets the value of the loyaltyBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoyaltyBrand(String value) {
        this.loyaltyBrand = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the enableNorthAmericanPrepayRates property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getEnableNorthAmericanPrepayRates() {
        return enableNorthAmericanPrepayRates;
    }

    /**
     * Sets the value of the enableNorthAmericanPrepayRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableNorthAmericanPrepayRates(Boolean value) {
        this.enableNorthAmericanPrepayRates = value;
    }

    /**
     * Gets the value of the coupons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coupons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoupons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCoupons() {
        if (coupons == null) {
            coupons = new ArrayList<String>();
        }
        return this.coupons;
    }

    /**
     * Gets the value of the redemptionDayCount property.
     * 
     */
    public int getRedemptionDayCount() {
        return redemptionDayCount;
    }

    /**
     * Sets the value of the redemptionDayCount property.
     * 
     */
    public void setRedemptionDayCount(int value) {
        this.redemptionDayCount = value;
    }

    /**
     * Gets the value of the bookingAgent property.
     * 
     * @return
     *     possible object is
     *     {@link BookingAgent }
     *     
     */
    public BookingAgent getBookingAgent() {
        return bookingAgent;
    }

    /**
     * Sets the value of the bookingAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingAgent }
     *     
     */
    public void setBookingAgent(BookingAgent value) {
        this.bookingAgent = value;
    }

}
