//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>The Request for retrieving rate and
 *                 Details
 *                 of
 *                 selected car class.</p>
 *             
 * 
 * <p>Java class for LevelOfServiceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelOfServiceRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.cts.product.rental.dto.messages/}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="meetAndGreetAccepted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelOfServiceRequest", propOrder = {
    "meetAndGreetAccepted"
})
public class LevelOfServiceRequest
    extends Request
    implements Serializable
{

    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean meetAndGreetAccepted;

    /**
     * Gets the value of the meetAndGreetAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getMeetAndGreetAccepted() {
        return meetAndGreetAccepted;
    }

    /**
     * Sets the value of the meetAndGreetAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMeetAndGreetAccepted(Boolean value) {
        this.meetAndGreetAccepted = value;
    }

}
