//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.cts.product.rental.dto.common.enums.BillingAccountTypeEnum;


/**
 * <p>Java class for ModifyPaymentRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModifyPaymentRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.ehi.gbo.rental.dto.messages/}ReservationModifyRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="paymentIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="billingAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="billingAccountType" type="{http://com.ehi.gbo.rental.dto.common.enums/}BillingAccountTypeEnum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModifyPaymentRequest", propOrder = {
    "paymentIds",
    "billingAccount",
    "billingAccountType"
})
public class ModifyPaymentRequest
    extends ReservationModifyRequest
    implements Serializable
{

    protected List<String> paymentIds;
    @XmlElement(required = true)
    protected String billingAccount;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BillingAccountTypeEnum billingAccountType;

    /**
     * Gets the value of the paymentIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPaymentIds() {
        if (paymentIds == null) {
            paymentIds = new ArrayList<String>();
        }
        return this.paymentIds;
    }

    /**
     * Gets the value of the billingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAccount() {
        return billingAccount;
    }

    /**
     * Sets the value of the billingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAccount(String value) {
        this.billingAccount = value;
    }

    /**
     * Gets the value of the billingAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link BillingAccountTypeEnum }
     *     
     */
    public BillingAccountTypeEnum getBillingAccountType() {
        return billingAccountType;
    }

    /**
     * Sets the value of the billingAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingAccountTypeEnum }
     *     
     */
    public void setBillingAccountType(BillingAccountTypeEnum value) {
        this.billingAccountType = value;
    }

}
