//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.cts.product.rental.dto.messages/")
package com.cts.product.rental.dto.messages;
