//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//

package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.cts.product.rental.dto.common.Coupon;
import com.cts.product.rental.dto.common.LevelOfService;
import com.cts.product.rental.dto.common.Mra;
import com.cts.product.rental.dto.common.Payment;
import com.cts.product.rental.dto.common.Policy;
import com.cts.product.rental.dto.common.enums.BookingAgent;
import com.cts.product.rental.dto.common.enums.PaymentProcessorEnum;
import com.cts.product.rental.dto.common.enums.ReservationSubStatus;
import com.cts.product.rental.dto.common.enums.RewardType;
import com.cts.product.rental.dto.common.enums.TravelPurposeEnum;
import com.cts.product.rental.dto.location.Location;
import com.cts.product.rental.dto.location.LocationDetail;
import com.cts.product.rental.dto.pricing.BaseExtraContent;
import com.cts.product.rental.dto.reservation.AdditionalDriver;
import com.cts.product.rental.dto.reservation.AdditionalInformationData;
import com.cts.product.rental.dto.reservation.AirlineInformation;
import com.cts.product.rental.dto.reservation.AnalyticData;
import com.cts.product.rental.dto.reservation.BillingAccount;
import com.cts.product.rental.dto.reservation.CancellationDetails;
import com.cts.product.rental.dto.reservation.CarClass;
import com.cts.product.rental.dto.reservation.CarClassDetails;
import com.cts.product.rental.dto.reservation.DeliveryCollectionDetails;
import com.cts.product.rental.dto.reservation.ExtendedDriverInfo;
import com.cts.product.rental.dto.reservation.ModificationConstraints;
import com.cts.product.rental.dto.reservation.PartnerRewardProgramDetail;
import com.cts.product.rental.dto.reservation.PrepayPolicies;
import com.cts.product.rental.dto.reservation.ReservationEligibility;
import com.cts.product.rental.dto.reservation.ReservationLink;
import com.cts.product.rental.dto.reservation.SelectedPaymentMethod;
import com.cts.product.rental.dto.reservation.TravelAdmin;
import com.cts.product.rental.dto.reservation.TravelAgent;
import com.cts.product.rental.dto.reservation.VehicleLogistics;
import com.cts.product.rental.dto.user.ContractDetails;
import com.cts.product.rental.dto.user.PaymentMethod;
import com.cts.product.rental.dto.user.ProfileDetails;
import com.cts.product.rental.dto.vehicle.VehicleFilter;

/**
 * <p>
 * Java class for ReservationResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ReservationResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.cts.product.rental.dto.messages/}Response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}resSessionId"/&gt;
 *         &lt;element name="pickupLocation" type="{http://com.cts.product.rental.dto.location/}LocationDetail"/&gt;
 *         &lt;element name="returnLocation" type="{http://com.cts.product.rental.dto.location/}LocationDetail"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}pickupTime"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}returnTime"/&gt;
 *         &lt;element name="paymentMethods" type="{http://com.cts.product.rental.dto.user/}PaymentMethod" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}afterHoursReturn"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}longTermRental"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}additionalInfoRequiredBeforeRates"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}contractNumber"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}renterAge"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}contractHasAdditionalBenefits"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}businessLeisureGenericDisclaimer"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}termsAndConditionsDocumentPath"/&gt;
 *         &lt;element name="driverInfo" type="{http://com.cts.product.rental.dto.reservation/}ExtendedDriverInfo"/&gt;
 *         &lt;element name="carClasses" type="{http://com.cts.product.rental.dto.reservation/}CarClass" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="carClassesFilters" type="{http://com.cts.product.rental.dto.vehicle/}VehicleFilter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="airlineInfo" type="{http://com.cts.product.rental.dto.reservation/}AirlineInformation"/&gt;
 *         &lt;element name="excludedExtras" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="additionalInformation" type="{http://com.cts.product.rental.dto.reservation/}AdditionalInformationData" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="selectedPaymentMethod" type="{http://com.cts.product.rental.dto.reservation/}SelectedPaymentMethod"/&gt;
 *         &lt;element name="cancellationDetails" type="{http://com.cts.product.rental.dto.reservation/}CancellationDetails"/&gt;
 *         &lt;element name="billingAccount" type="{http://com.cts.product.rental.dto.reservation/}BillingAccount"/&gt;
 *         &lt;element name="alternativePickupLocations" type="{http://com.cts.product.rental.dto.location/}Location" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="alternativeReturnLocations" type="{http://com.cts.product.rental.dto.location/}Location" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="carClassDetails" type="{http://com.cts.product.rental.dto.reservation/}CarClassDetails"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}confirmationNumber"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}ticketNumber"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}reservationStatus"/&gt;
 *         &lt;element name="upgradeVehiclePossible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="upgradeCarClassDetails" type="{http://com.cts.product.rental.dto.reservation/}CarClassDetails" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="extrasNoLongerAvailableAfterUpgrade" type="{http://com.cts.product.rental.dto.pricing/}BaseExtraContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="contractDetails" type="{http://com.cts.product.rental.dto.user/}ContractDetails"/&gt;
 *         &lt;element name="reservationEligibility" type="{http://com.cts.product.rental.dto.reservation/}ReservationEligibility"/&gt;
 *         &lt;element name="policies" type="{http://com.cts.product.rental.dto.common/}Policy" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="deliveryAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="collectionAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="afterHoursReturnSelected" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="afterHoursPickupSelected" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="doNotRentIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="vehicleLogistics" type="{http://com.cts.product.rental.dto.reservation/}vehicleLogistics"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}prepaySelected"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}cancelRebook"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}ePlusPointsUsed"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}eplusPointsEarned"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}redemptionDayCount"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}eplusTotalAvailablePoints"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}europeanUnionCountry"/&gt;
 *         &lt;element name="payments" type="{http://com.cts.product.rental.dto.common/}Payment" maxOccurs="2" minOccurs="0"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}travelPurpose"/&gt;
 *         &lt;element name="prefillDeepLinkUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}rulesOfTheRoadUrl"/&gt;
 *         &lt;element name="onRequestCarClassSelected" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="prepayPolicies" type="{http://com.cts.product.rental.dto.reservation/}PrepayPolicies"/&gt;
 *         &lt;element name="rentalChecklist" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="keyFactsPolicies" type="{http://com.cts.product.rental.dto.common/}Policy" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="signatureAccount" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="partnerRewardProgram" type="{http://com.cts.product.rental.dto.reservation/}PartnerRewardProgramDetail" minOccurs="0"/&gt;
 *         &lt;element name="protectionsRequiredAtCounter" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="protectionsRequiredAtCounterText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="licenseeName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="visitDomainUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="blockAssociateProfile" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="deliveryCollection" type="{http://com.cts.product.rental.dto.reservation/}DeliveryCollectionDetails"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.reservation/}iataNumber"/&gt;
 *         &lt;element name="blockModifyPickupLocation" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="collectNewPaymentCardInModify" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="prepayPaymentProcessor" type="{http://com.cts.product.rental.dto.common.enums/}PaymentProcessorEnum"/&gt;
 *         &lt;element name="blockPartnerRewards" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="rewardType" type="{http://com.cts.product.rental.dto.common.enums/}RewardType"/&gt;
 *         &lt;element name="pickupReservation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="levelOfService" type="{http://com.cts.product.rental.dto.common/}levelOfService"/&gt;
 *         &lt;element name="currencyConversionDisclaimerText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="priorityServiceAvailableAtLocation" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mra" type="{http://com.cts.product.rental.dto.common/}mra"/&gt;
 *         &lt;element name="analyticData" type="{http://com.cts.product.rental.dto.reservation/}AnalyticData"/&gt;
 *         &lt;element name="coupons" type="{http://com.cts.product.rental.dto.common/}Coupon" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="bookingAgent" type="{http://com.cts.product.rental.dto.common.enums/}BookingAgent"/&gt;
 *         &lt;element name="travelAdmin" type="{http://com.cts.product.rental.dto.reservation/}TravelAdmin"/&gt;
 *         &lt;element name="travelAgent" type="{http://com.cts.product.rental.dto.reservation/}TravelAgent"/&gt;
 *         &lt;element name="modificationConstraints" type="{http://com.cts.product.rental.dto.reservation/}ModificationConstraints"/&gt;
 *         &lt;element name="profileDetails" type="{http://com.cts.product.rental.dto.user/}ProfileDetails"/&gt;
 *         &lt;element name="numberOfAdditionalDriversAllowed" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="additionalDrivers" type="{http://com.cts.product.rental.dto.reservation/}AdditionalDriver" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="remainingDaysForPickUp" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="reservationSubStatus" type="{http://com.cts.product.rental.dto.common.enums/}ReservationSubStatus"/&gt;
 *         &lt;element name="links" type="{http://com.cts.product.rental.dto.reservation/}ReservationLink" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="vriEligible" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="OnRequestAfterHours" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="oneClickDefaultCarClass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReservationResponse", propOrder = { "resSessionId", "pickupLocation", "returnLocation", "pickupTime",
	"returnTime", "paymentMethods", "afterHoursReturn", "longTermRental", "additionalInfoRequiredBeforeRates",
	"contractNumber", "renterAge", "contractHasAdditionalBenefits", "businessLeisureGenericDisclaimer",
	"termsAndConditionsDocumentPath", "driverInfo", "carClasses", "carClassesFilters", "airlineInfo",
	"excludedExtras", "additionalInformation", "selectedPaymentMethod", "cancellationDetails", "billingAccount",
	"alternativePickupLocations", "alternativeReturnLocations", "carClassDetails", "confirmationNumber",
	"ticketNumber", "reservationStatus", "upgradeVehiclePossible", "upgradeCarClassDetails",
	"extrasNoLongerAvailableAfterUpgrades", "contractDetails", "reservationEligibility", "policies",
	"deliveryAllowed", "collectionAllowed", "afterHoursReturnSelected", "afterHoursPickupSelected",
	"doNotRentIndicator", "vehicleLogistics", "prepaySelected", "cancelRebook", "ePlusPointsUsed",
	"eplusPointsEarned", "redemptionDayCount", "eplusTotalAvailablePoints", "europeanUnionCountry", "payments",
	"travelPurpose", "prefillDeepLinkUrl", "rulesOfTheRoadUrl", "onRequestCarClassSelected", "prepayPolicies",
	"rentalChecklists", "keyFactsPolicies", "signatureAccount", "partnerRewardProgram",
	"protectionsRequiredAtCounter", "protectionsRequiredAtCounterText", "licenseeName", "visitDomainUrl",
	"blockAssociateProfile", "deliveryCollection", "iataNumber", "blockModifyPickupLocation",
	"collectNewPaymentCardInModify", "prepayPaymentProcessor", "blockPartnerRewards", "rewardType",
	"pickupReservation", "levelOfService", "currencyConversionDisclaimerText", "priorityServiceAvailableAtLocation",
	"mra", "analyticData", "coupons", "bookingAgent", "travelAdmin", "travelAgent", "modificationConstraints",
	"profileDetails", "numberOfAdditionalDriversAllowed", "additionalDrivers", "remainingDaysForPickUp",
	"reservationSubStatus", "links", "vriEligible", "onRequestAfterHours", "oneClickDefaultCarClass" })
public class ReservationResponse extends Response implements Serializable {

    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String resSessionId;
    @XmlElement(required = true)
    protected LocationDetail pickupLocation;
    @XmlElement(required = true)
    protected LocationDetail returnLocation;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String pickupTime;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String returnTime;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String createdTime;
    protected List<PaymentMethod> paymentMethods;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Boolean.class, nillable = true)
    protected Boolean afterHoursReturn;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Boolean.class, nillable = true)
    protected Boolean longTermRental;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Boolean.class, nillable = true)
    protected Boolean additionalInfoRequiredBeforeRates;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String contractNumber;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Integer.class, nillable = true)
    protected Integer renterAge;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/")
    protected boolean contractHasAdditionalBenefits;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String businessLeisureGenericDisclaimer;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String termsAndConditionsDocumentPath;
    @XmlElement(required = true)
    protected ExtendedDriverInfo driverInfo;
    protected List<CarClass> carClasses;
    protected List<VehicleFilter> carClassesFilters;
    @XmlElement(required = true)
    protected AirlineInformation airlineInfo;
    protected List<String> excludedExtras;
    protected List<AdditionalInformationData> additionalInformation;
    @XmlElement(required = true)
    protected SelectedPaymentMethod selectedPaymentMethod;
    @XmlElement(required = true)
    protected CancellationDetails cancellationDetails;
    @XmlElement(required = true)
    protected BillingAccount billingAccount;
    protected List<Location> alternativePickupLocations;
    protected List<Location> alternativeReturnLocations;
    @XmlElement(required = true)
    protected CarClassDetails carClassDetails;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String confirmationNumber;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String ticketNumber;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String reservationStatus;
    protected boolean upgradeVehiclePossible;
    protected List<CarClassDetails> upgradeCarClassDetails;
    @XmlElement(name = "extrasNoLongerAvailableAfterUpgrade")
    protected List<BaseExtraContent> extrasNoLongerAvailableAfterUpgrades;
    @XmlElement(required = true)
    protected ContractDetails contractDetails;
    @XmlElement(required = true)
    protected ReservationEligibility reservationEligibility;
    protected List<Policy> policies;
    protected boolean deliveryAllowed;
    protected boolean collectionAllowed;
    protected boolean afterHoursReturnSelected;
    protected boolean afterHoursPickupSelected;
    protected boolean doNotRentIndicator;
    @XmlElement(required = true)
    protected VehicleLogistics vehicleLogistics;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/")
    protected boolean prepaySelected;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/")
    protected boolean cancelRebook;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Integer.class, nillable = true)
    protected Integer ePlusPointsUsed;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Integer.class, nillable = true)
    protected Integer eplusPointsEarned;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Integer.class, nillable = true)
    protected Integer redemptionDayCount;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true, type = Integer.class, nillable = true)
    protected Integer eplusTotalAvailablePoints;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/")
    protected boolean europeanUnionCountry;
    protected List<Payment> payments;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    @XmlSchemaType(name = "string")
    protected TravelPurposeEnum travelPurpose;
    @XmlElement(required = true)
    protected String prefillDeepLinkUrl;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String rulesOfTheRoadUrl;
    protected boolean onRequestCarClassSelected;
    @XmlElement(required = true)
    protected PrepayPolicies prepayPolicies;
    @XmlElement(name = "rentalChecklist")
    protected List<String> rentalChecklists;
    protected List<Policy> keyFactsPolicies;
    protected boolean signatureAccount;
    protected PartnerRewardProgramDetail partnerRewardProgram;
    protected List<String> protectionsRequiredAtCounter;
    @XmlElement(required = true, nillable = true)
    protected String protectionsRequiredAtCounterText;
    @XmlElement(required = true, nillable = true)
    protected String licenseeName;
    @XmlElement(required = true)
    protected String visitDomainUrl;
    protected boolean blockAssociateProfile;
    @XmlElement(required = true)
    protected DeliveryCollectionDetails deliveryCollection;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.reservation/", required = true)
    protected String iataNumber;
    protected boolean blockModifyPickupLocation;
    protected Boolean collectNewPaymentCardInModify;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PaymentProcessorEnum prepayPaymentProcessor;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean blockPartnerRewards;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected RewardType rewardType;
    protected Boolean pickupReservation;
    @XmlElement(required = true)
    protected LevelOfService levelOfService;
    @XmlElement(required = true)
    protected String currencyConversionDisclaimerText;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean priorityServiceAvailableAtLocation;
    @XmlElement(required = true)
    protected Mra mra;
    @XmlElement(required = true)
    protected AnalyticData analyticData;
    protected List<Coupon> coupons;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "string")
    protected BookingAgent bookingAgent;
    @XmlElement(required = true)
    protected TravelAdmin travelAdmin;
    @XmlElement(required = true, nillable = true)
    protected TravelAgent travelAgent;
    @XmlElement(required = true)
    protected ModificationConstraints modificationConstraints;
    @XmlElement(required = true)
    protected ProfileDetails profileDetails;
    protected int numberOfAdditionalDriversAllowed;
    protected List<AdditionalDriver> additionalDrivers;
    @XmlElement(required = true)
    protected BigInteger remainingDaysForPickUp;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ReservationSubStatus reservationSubStatus;
    protected List<ReservationLink> links;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean vriEligible;
    @XmlElement(name = "OnRequestAfterHours", required = true, type = Boolean.class, nillable = true)
    protected Boolean onRequestAfterHours;
    @XmlElement(required = true)
    protected String oneClickDefaultCarClass;

    /**
     * Gets the value of the resSessionId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getResSessionId() {
	return resSessionId;
    }

    /**
     * Sets the value of the resSessionId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setResSessionId(String value) {
	this.resSessionId = value;
    }

    /**
     * Gets the value of the pickupLocation property.
     * 
     * @return possible object is {@link LocationDetail }
     * 
     */
    public LocationDetail getPickupLocation() {
	return pickupLocation;
    }

    /**
     * Sets the value of the pickupLocation property.
     * 
     * @param value
     *            allowed object is {@link LocationDetail }
     * 
     */
    public void setPickupLocation(LocationDetail value) {
	this.pickupLocation = value;
    }

    /**
     * Gets the value of the returnLocation property.
     * 
     * @return possible object is {@link LocationDetail }
     * 
     */
    public LocationDetail getReturnLocation() {
	return returnLocation;
    }

    /**
     * Sets the value of the returnLocation property.
     * 
     * @param value
     *            allowed object is {@link LocationDetail }
     * 
     */
    public void setReturnLocation(LocationDetail value) {
	this.returnLocation = value;
    }

    /**
     * Gets the value of the pickupTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPickupTime() {
	return pickupTime;
    }

    /**
     * Sets the value of the pickupTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPickupTime(String value) {
	this.pickupTime = value;
    }

    /**
     * Gets the value of the returnTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReturnTime() {
	return returnTime;
    }

    /**
     * Sets the value of the returnTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReturnTime(String value) {
	this.returnTime = value;
    }

    /**
     * Gets the value of the createdTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCreatedTime() {
	return createdTime;
    }

    /**
     * Sets the value of the createdTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCreatedTime(String value) {
	this.createdTime = value;
    }

    /**
     * Gets the value of the paymentMethods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the paymentMethods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPaymentMethods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link PaymentMethod
     * }
     * 
     * 
     */
    public List<PaymentMethod> getPaymentMethods() {
	if (paymentMethods == null) {
	    paymentMethods = new ArrayList<PaymentMethod>();
	}
	return this.paymentMethods;
    }

    /**
     * Gets the value of the afterHoursReturn property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getAfterHoursReturn() {
	return afterHoursReturn;
    }

    /**
     * Sets the value of the afterHoursReturn property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setAfterHoursReturn(Boolean value) {
	this.afterHoursReturn = value;
    }

    /**
     * Gets the value of the longTermRental property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getLongTermRental() {
	return longTermRental;
    }

    /**
     * Sets the value of the longTermRental property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setLongTermRental(Boolean value) {
	this.longTermRental = value;
    }

    /**
     * Gets the value of the additionalInfoRequiredBeforeRates property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getAdditionalInfoRequiredBeforeRates() {
	return additionalInfoRequiredBeforeRates;
    }

    /**
     * Sets the value of the additionalInfoRequiredBeforeRates property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setAdditionalInfoRequiredBeforeRates(Boolean value) {
	this.additionalInfoRequiredBeforeRates = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getContractNumber() {
	return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setContractNumber(String value) {
	this.contractNumber = value;
    }

    /**
     * Gets the value of the renterAge property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getRenterAge() {
	return renterAge;
    }

    /**
     * Sets the value of the renterAge property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setRenterAge(Integer value) {
	this.renterAge = value;
    }

    /**
     * Gets the value of the contractHasAdditionalBenefits property.
     * 
     */
    public boolean isContractHasAdditionalBenefits() {
	return contractHasAdditionalBenefits;
    }

    /**
     * Sets the value of the contractHasAdditionalBenefits property.
     * 
     */
    public void setContractHasAdditionalBenefits(boolean value) {
	this.contractHasAdditionalBenefits = value;
    }

    /**
     * Gets the value of the businessLeisureGenericDisclaimer property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBusinessLeisureGenericDisclaimer() {
	return businessLeisureGenericDisclaimer;
    }

    /**
     * Sets the value of the businessLeisureGenericDisclaimer property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBusinessLeisureGenericDisclaimer(String value) {
	this.businessLeisureGenericDisclaimer = value;
    }

    /**
     * Gets the value of the termsAndConditionsDocumentPath property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTermsAndConditionsDocumentPath() {
	return termsAndConditionsDocumentPath;
    }

    /**
     * Sets the value of the termsAndConditionsDocumentPath property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTermsAndConditionsDocumentPath(String value) {
	this.termsAndConditionsDocumentPath = value;
    }

    /**
     * Gets the value of the driverInfo property.
     * 
     * @return possible object is {@link ExtendedDriverInfo }
     * 
     */
    public ExtendedDriverInfo getDriverInfo() {
	return driverInfo;
    }

    /**
     * Sets the value of the driverInfo property.
     * 
     * @param value
     *            allowed object is {@link ExtendedDriverInfo }
     * 
     */
    public void setDriverInfo(ExtendedDriverInfo value) {
	this.driverInfo = value;
    }

    /**
     * Gets the value of the carClasses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the carClasses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCarClasses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CarClass }
     * 
     * 
     */
    public List<CarClass> getCarClasses() {
	if (carClasses == null) {
	    carClasses = new ArrayList<CarClass>();
	}
	return this.carClasses;
    }

    /**
     * Gets the value of the carClassesFilters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the carClassesFilters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCarClassesFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link VehicleFilter
     * }
     * 
     * 
     */
    public List<VehicleFilter> getCarClassesFilters() {
	if (carClassesFilters == null) {
	    carClassesFilters = new ArrayList<VehicleFilter>();
	}
	return this.carClassesFilters;
    }

    /**
     * Gets the value of the airlineInfo property.
     * 
     * @return possible object is {@link AirlineInformation }
     * 
     */
    public AirlineInformation getAirlineInfo() {
	return airlineInfo;
    }

    /**
     * Sets the value of the airlineInfo property.
     * 
     * @param value
     *            allowed object is {@link AirlineInformation }
     * 
     */
    public void setAirlineInfo(AirlineInformation value) {
	this.airlineInfo = value;
    }

    /**
     * Gets the value of the excludedExtras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the excludedExtras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExcludedExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getExcludedExtras() {
	if (excludedExtras == null) {
	    excludedExtras = new ArrayList<String>();
	}
	return this.excludedExtras;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the additionalInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAdditionalInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInformationData }
     * 
     * 
     */
    public List<AdditionalInformationData> getAdditionalInformation() {
	if (additionalInformation == null) {
	    additionalInformation = new ArrayList<AdditionalInformationData>();
	}
	return this.additionalInformation;
    }

    /**
     * Gets the value of the selectedPaymentMethod property.
     * 
     * @return possible object is {@link SelectedPaymentMethod }
     * 
     */
    public SelectedPaymentMethod getSelectedPaymentMethod() {
	return selectedPaymentMethod;
    }

    /**
     * Sets the value of the selectedPaymentMethod property.
     * 
     * @param value
     *            allowed object is {@link SelectedPaymentMethod }
     * 
     */
    public void setSelectedPaymentMethod(SelectedPaymentMethod value) {
	this.selectedPaymentMethod = value;
    }

    /**
     * Gets the value of the cancellationDetails property.
     * 
     * @return possible object is {@link CancellationDetails }
     * 
     */
    public CancellationDetails getCancellationDetails() {
	return cancellationDetails;
    }

    /**
     * Sets the value of the cancellationDetails property.
     * 
     * @param value
     *            allowed object is {@link CancellationDetails }
     * 
     */
    public void setCancellationDetails(CancellationDetails value) {
	this.cancellationDetails = value;
    }

    /**
     * Gets the value of the billingAccount property.
     * 
     * @return possible object is {@link BillingAccount }
     * 
     */
    public BillingAccount getBillingAccount() {
	return billingAccount;
    }

    /**
     * Sets the value of the billingAccount property.
     * 
     * @param value
     *            allowed object is {@link BillingAccount }
     * 
     */
    public void setBillingAccount(BillingAccount value) {
	this.billingAccount = value;
    }

    /**
     * Gets the value of the alternativePickupLocations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the alternativePickupLocations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAlternativePickupLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Location }
     * 
     * 
     */
    public List<Location> getAlternativePickupLocations() {
	if (alternativePickupLocations == null) {
	    alternativePickupLocations = new ArrayList<Location>();
	}
	return this.alternativePickupLocations;
    }

    /**
     * Gets the value of the alternativeReturnLocations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the alternativeReturnLocations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAlternativeReturnLocations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Location }
     * 
     * 
     */
    public List<Location> getAlternativeReturnLocations() {
	if (alternativeReturnLocations == null) {
	    alternativeReturnLocations = new ArrayList<Location>();
	}
	return this.alternativeReturnLocations;
    }

    /**
     * Gets the value of the carClassDetails property.
     * 
     * @return possible object is {@link CarClassDetails }
     * 
     */
    public CarClassDetails getCarClassDetails() {
	return carClassDetails;
    }

    /**
     * Sets the value of the carClassDetails property.
     * 
     * @param value
     *            allowed object is {@link CarClassDetails }
     * 
     */
    public void setCarClassDetails(CarClassDetails value) {
	this.carClassDetails = value;
    }

    /**
     * Gets the value of the confirmationNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getConfirmationNumber() {
	return confirmationNumber;
    }

    /**
     * Sets the value of the confirmationNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setConfirmationNumber(String value) {
	this.confirmationNumber = value;
    }

    /**
     * Gets the value of the ticketNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTicketNumber() {
	return ticketNumber;
    }

    /**
     * Sets the value of the ticketNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTicketNumber(String value) {
	this.ticketNumber = value;
    }

    /**
     * Gets the value of the reservationStatus property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReservationStatus() {
	return reservationStatus;
    }

    /**
     * Sets the value of the reservationStatus property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setReservationStatus(String value) {
	this.reservationStatus = value;
    }

    /**
     * Gets the value of the upgradeVehiclePossible property.
     * 
     */
    public boolean isUpgradeVehiclePossible() {
	return upgradeVehiclePossible;
    }

    /**
     * Sets the value of the upgradeVehiclePossible property.
     * 
     */
    public void setUpgradeVehiclePossible(boolean value) {
	this.upgradeVehiclePossible = value;
    }

    /**
     * Gets the value of the upgradeCarClassDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the upgradeCarClassDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getUpgradeCarClassDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CarClassDetails }
     * 
     * 
     */
    public List<CarClassDetails> getUpgradeCarClassDetails() {
	if (upgradeCarClassDetails == null) {
	    upgradeCarClassDetails = new ArrayList<CarClassDetails>();
	}
	return this.upgradeCarClassDetails;
    }

    /**
     * Gets the value of the extrasNoLongerAvailableAfterUpgrades property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the extrasNoLongerAvailableAfterUpgrades property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getExtrasNoLongerAvailableAfterUpgrades().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseExtraContent }
     * 
     * 
     */
    public List<BaseExtraContent> getExtrasNoLongerAvailableAfterUpgrades() {
	if (extrasNoLongerAvailableAfterUpgrades == null) {
	    extrasNoLongerAvailableAfterUpgrades = new ArrayList<BaseExtraContent>();
	}
	return this.extrasNoLongerAvailableAfterUpgrades;
    }

    /**
     * Gets the value of the contractDetails property.
     * 
     * @return possible object is {@link ContractDetails }
     * 
     */
    public ContractDetails getContractDetails() {
	return contractDetails;
    }

    /**
     * Sets the value of the contractDetails property.
     * 
     * @param value
     *            allowed object is {@link ContractDetails }
     * 
     */
    public void setContractDetails(ContractDetails value) {
	this.contractDetails = value;
    }

    /**
     * Gets the value of the reservationEligibility property.
     * 
     * @return possible object is {@link ReservationEligibility }
     * 
     */
    public ReservationEligibility getReservationEligibility() {
	return reservationEligibility;
    }

    /**
     * Sets the value of the reservationEligibility property.
     * 
     * @param value
     *            allowed object is {@link ReservationEligibility }
     * 
     */
    public void setReservationEligibility(ReservationEligibility value) {
	this.reservationEligibility = value;
    }

    /**
     * Gets the value of the policies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the policies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPolicies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Policy }
     * 
     * 
     */
    public List<Policy> getPolicies() {
	if (policies == null) {
	    policies = new ArrayList<Policy>();
	}
	return this.policies;
    }

    /**
     * Gets the value of the deliveryAllowed property.
     * 
     */
    public boolean isDeliveryAllowed() {
	return deliveryAllowed;
    }

    /**
     * Sets the value of the deliveryAllowed property.
     * 
     */
    public void setDeliveryAllowed(boolean value) {
	this.deliveryAllowed = value;
    }

    /**
     * Gets the value of the collectionAllowed property.
     * 
     */
    public boolean isCollectionAllowed() {
	return collectionAllowed;
    }

    /**
     * Sets the value of the collectionAllowed property.
     * 
     */
    public void setCollectionAllowed(boolean value) {
	this.collectionAllowed = value;
    }

    /**
     * Gets the value of the afterHoursReturnSelected property.
     * 
     */
    public boolean isAfterHoursReturnSelected() {
	return afterHoursReturnSelected;
    }

    /**
     * Sets the value of the afterHoursReturnSelected property.
     * 
     */
    public void setAfterHoursReturnSelected(boolean value) {
	this.afterHoursReturnSelected = value;
    }

    /**
     * Gets the value of the afterHoursPickupSelected property.
     * 
     */
    public boolean isAfterHoursPickupSelected() {
	return afterHoursPickupSelected;
    }

    /**
     * Sets the value of the afterHoursPickupSelected property.
     * 
     */
    public void setAfterHoursPickupSelected(boolean value) {
	this.afterHoursPickupSelected = value;
    }

    /**
     * Gets the value of the doNotRentIndicator property.
     * 
     */
    public boolean isDoNotRentIndicator() {
	return doNotRentIndicator;
    }

    /**
     * Sets the value of the doNotRentIndicator property.
     * 
     */
    public void setDoNotRentIndicator(boolean value) {
	this.doNotRentIndicator = value;
    }

    /**
     * Gets the value of the vehicleLogistics property.
     * 
     * @return possible object is {@link VehicleLogistics }
     * 
     */
    public VehicleLogistics getVehicleLogistics() {
	return vehicleLogistics;
    }

    /**
     * Sets the value of the vehicleLogistics property.
     * 
     * @param value
     *            allowed object is {@link VehicleLogistics }
     * 
     */
    public void setVehicleLogistics(VehicleLogistics value) {
	this.vehicleLogistics = value;
    }

    /**
     * Gets the value of the prepaySelected property.
     * 
     */
    public boolean isPrepaySelected() {
	return prepaySelected;
    }

    /**
     * Sets the value of the prepaySelected property.
     * 
     */
    public void setPrepaySelected(boolean value) {
	this.prepaySelected = value;
    }

    /**
     * Gets the value of the cancelRebook property.
     * 
     */
    public boolean isCancelRebook() {
	return cancelRebook;
    }

    /**
     * Sets the value of the cancelRebook property.
     * 
     */
    public void setCancelRebook(boolean value) {
	this.cancelRebook = value;
    }

    /**
     * Gets the value of the ePlusPointsUsed property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getEPlusPointsUsed() {
	return ePlusPointsUsed;
    }

    /**
     * Sets the value of the ePlusPointsUsed property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setEPlusPointsUsed(Integer value) {
	this.ePlusPointsUsed = value;
    }

    /**
     * Gets the value of the eplusPointsEarned property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getEplusPointsEarned() {
	return eplusPointsEarned;
    }

    /**
     * Sets the value of the eplusPointsEarned property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setEplusPointsEarned(Integer value) {
	this.eplusPointsEarned = value;
    }

    /**
     * Gets the value of the redemptionDayCount property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getRedemptionDayCount() {
	return redemptionDayCount;
    }

    /**
     * Sets the value of the redemptionDayCount property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setRedemptionDayCount(Integer value) {
	this.redemptionDayCount = value;
    }

    /**
     * Gets the value of the eplusTotalAvailablePoints property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getEplusTotalAvailablePoints() {
	return eplusTotalAvailablePoints;
    }

    /**
     * Sets the value of the eplusTotalAvailablePoints property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setEplusTotalAvailablePoints(Integer value) {
	this.eplusTotalAvailablePoints = value;
    }

    /**
     * Gets the value of the europeanUnionCountry property.
     * 
     */
    public boolean isEuropeanUnionCountry() {
	return europeanUnionCountry;
    }

    /**
     * Sets the value of the europeanUnionCountry property.
     * 
     */
    public void setEuropeanUnionCountry(boolean value) {
	this.europeanUnionCountry = value;
    }

    /**
     * Gets the value of the payments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the payments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPayments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Payment }
     * 
     * 
     */
    public List<Payment> getPayments() {
	if (payments == null) {
	    payments = new ArrayList<Payment>();
	}
	return this.payments;
    }

    /**
     * Gets the value of the travelPurpose property.
     * 
     * @return possible object is {@link TravelPurposeEnum }
     * 
     */
    public TravelPurposeEnum getTravelPurpose() {
	return travelPurpose;
    }

    /**
     * Sets the value of the travelPurpose property.
     * 
     * @param value
     *            allowed object is {@link TravelPurposeEnum }
     * 
     */
    public void setTravelPurpose(TravelPurposeEnum value) {
	this.travelPurpose = value;
    }

    /**
     * Gets the value of the prefillDeepLinkUrl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPrefillDeepLinkUrl() {
	return prefillDeepLinkUrl;
    }

    /**
     * Sets the value of the prefillDeepLinkUrl property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPrefillDeepLinkUrl(String value) {
	this.prefillDeepLinkUrl = value;
    }

    /**
     * Gets the value of the rulesOfTheRoadUrl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRulesOfTheRoadUrl() {
	return rulesOfTheRoadUrl;
    }

    /**
     * Sets the value of the rulesOfTheRoadUrl property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRulesOfTheRoadUrl(String value) {
	this.rulesOfTheRoadUrl = value;
    }

    /**
     * Gets the value of the onRequestCarClassSelected property.
     * 
     */
    public boolean isOnRequestCarClassSelected() {
	return onRequestCarClassSelected;
    }

    /**
     * Sets the value of the onRequestCarClassSelected property.
     * 
     */
    public void setOnRequestCarClassSelected(boolean value) {
	this.onRequestCarClassSelected = value;
    }

    /**
     * Gets the value of the prepayPolicies property.
     * 
     * @return possible object is {@link PrepayPolicies }
     * 
     */
    public PrepayPolicies getPrepayPolicies() {
	return prepayPolicies;
    }

    /**
     * Sets the value of the prepayPolicies property.
     * 
     * @param value
     *            allowed object is {@link PrepayPolicies }
     * 
     */
    public void setPrepayPolicies(PrepayPolicies value) {
	this.prepayPolicies = value;
    }

    /**
     * Gets the value of the rentalChecklists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the rentalChecklists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRentalChecklists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getRentalChecklists() {
	if (rentalChecklists == null) {
	    rentalChecklists = new ArrayList<String>();
	}
	return this.rentalChecklists;
    }

    /**
     * Gets the value of the keyFactsPolicies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the keyFactsPolicies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getKeyFactsPolicies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Policy }
     * 
     * 
     */
    public List<Policy> getKeyFactsPolicies() {
	if (keyFactsPolicies == null) {
	    keyFactsPolicies = new ArrayList<Policy>();
	}
	return this.keyFactsPolicies;
    }

    /**
     * Gets the value of the signatureAccount property.
     * 
     */
    public boolean isSignatureAccount() {
	return signatureAccount;
    }

    /**
     * Sets the value of the signatureAccount property.
     * 
     */
    public void setSignatureAccount(boolean value) {
	this.signatureAccount = value;
    }

    /**
     * Gets the value of the partnerRewardProgram property.
     * 
     * @return possible object is {@link PartnerRewardProgramDetail }
     * 
     */
    public PartnerRewardProgramDetail getPartnerRewardProgram() {
	return partnerRewardProgram;
    }

    /**
     * Sets the value of the partnerRewardProgram property.
     * 
     * @param value
     *            allowed object is {@link PartnerRewardProgramDetail }
     * 
     */
    public void setPartnerRewardProgram(PartnerRewardProgramDetail value) {
	this.partnerRewardProgram = value;
    }

    /**
     * Gets the value of the protectionsRequiredAtCounter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the protectionsRequiredAtCounter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getProtectionsRequiredAtCounter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getProtectionsRequiredAtCounter() {
	if (protectionsRequiredAtCounter == null) {
	    protectionsRequiredAtCounter = new ArrayList<String>();
	}
	return this.protectionsRequiredAtCounter;
    }

    /**
     * Gets the value of the protectionsRequiredAtCounterText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProtectionsRequiredAtCounterText() {
	return protectionsRequiredAtCounterText;
    }

    /**
     * Sets the value of the protectionsRequiredAtCounterText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProtectionsRequiredAtCounterText(String value) {
	this.protectionsRequiredAtCounterText = value;
    }

    /**
     * Gets the value of the licenseeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLicenseeName() {
	return licenseeName;
    }

    /**
     * Sets the value of the licenseeName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLicenseeName(String value) {
	this.licenseeName = value;
    }

    /**
     * Gets the value of the visitDomainUrl property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVisitDomainUrl() {
	return visitDomainUrl;
    }

    /**
     * Sets the value of the visitDomainUrl property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVisitDomainUrl(String value) {
	this.visitDomainUrl = value;
    }

    /**
     * Gets the value of the blockAssociateProfile property.
     * 
     */
    public boolean isBlockAssociateProfile() {
	return blockAssociateProfile;
    }

    /**
     * Sets the value of the blockAssociateProfile property.
     * 
     */
    public void setBlockAssociateProfile(boolean value) {
	this.blockAssociateProfile = value;
    }

    /**
     * Gets the value of the deliveryCollection property.
     * 
     * @return possible object is {@link DeliveryCollectionDetails }
     * 
     */
    public DeliveryCollectionDetails getDeliveryCollection() {
	return deliveryCollection;
    }

    /**
     * Sets the value of the deliveryCollection property.
     * 
     * @param value
     *            allowed object is {@link DeliveryCollectionDetails }
     * 
     */
    public void setDeliveryCollection(DeliveryCollectionDetails value) {
	this.deliveryCollection = value;
    }

    /**
     * Gets the value of the iataNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIataNumber() {
	return iataNumber;
    }

    /**
     * Sets the value of the iataNumber property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIataNumber(String value) {
	this.iataNumber = value;
    }

    /**
     * Gets the value of the blockModifyPickupLocation property.
     * 
     */
    public boolean isBlockModifyPickupLocation() {
	return blockModifyPickupLocation;
    }

    /**
     * Sets the value of the blockModifyPickupLocation property.
     * 
     */
    public void setBlockModifyPickupLocation(boolean value) {
	this.blockModifyPickupLocation = value;
    }

    /**
     * Gets the value of the collectNewPaymentCardInModify property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getCollectNewPaymentCardInModify() {
	return collectNewPaymentCardInModify;
    }

    /**
     * Sets the value of the collectNewPaymentCardInModify property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setCollectNewPaymentCardInModify(Boolean value) {
	this.collectNewPaymentCardInModify = value;
    }

    /**
     * Gets the value of the prepayPaymentProcessor property.
     * 
     * @return possible object is {@link PaymentProcessorEnum }
     * 
     */
    public PaymentProcessorEnum getPrepayPaymentProcessor() {
	return prepayPaymentProcessor;
    }

    /**
     * Sets the value of the prepayPaymentProcessor property.
     * 
     * @param value
     *            allowed object is {@link PaymentProcessorEnum }
     * 
     */
    public void setPrepayPaymentProcessor(PaymentProcessorEnum value) {
	this.prepayPaymentProcessor = value;
    }

    /**
     * Gets the value of the blockPartnerRewards property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getBlockPartnerRewards() {
	return blockPartnerRewards;
    }

    /**
     * Sets the value of the blockPartnerRewards property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setBlockPartnerRewards(Boolean value) {
	this.blockPartnerRewards = value;
    }

    /**
     * Gets the value of the rewardType property.
     * 
     * @return possible object is {@link RewardType }
     * 
     */
    public RewardType getRewardType() {
	return rewardType;
    }

    /**
     * Sets the value of the rewardType property.
     * 
     * @param value
     *            allowed object is {@link RewardType }
     * 
     */
    public void setRewardType(RewardType value) {
	this.rewardType = value;
    }

    /**
     * Gets the value of the pickupReservation property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getPickupReservation() {
	return pickupReservation;
    }

    /**
     * Sets the value of the pickupReservation property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setPickupReservation(Boolean value) {
	this.pickupReservation = value;
    }

    /**
     * Gets the value of the levelOfService property.
     * 
     * @return possible object is {@link LevelOfService }
     * 
     */
    public LevelOfService getLevelOfService() {
	return levelOfService;
    }

    /**
     * Sets the value of the levelOfService property.
     * 
     * @param value
     *            allowed object is {@link LevelOfService }
     * 
     */
    public void setLevelOfService(LevelOfService value) {
	this.levelOfService = value;
    }

    /**
     * Gets the value of the currencyConversionDisclaimerText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrencyConversionDisclaimerText() {
	return currencyConversionDisclaimerText;
    }

    /**
     * Sets the value of the currencyConversionDisclaimerText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCurrencyConversionDisclaimerText(String value) {
	this.currencyConversionDisclaimerText = value;
    }

    /**
     * Gets the value of the priorityServiceAvailableAtLocation property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getPriorityServiceAvailableAtLocation() {
	return priorityServiceAvailableAtLocation;
    }

    /**
     * Sets the value of the priorityServiceAvailableAtLocation property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setPriorityServiceAvailableAtLocation(Boolean value) {
	this.priorityServiceAvailableAtLocation = value;
    }

    /**
     * Gets the value of the mra property.
     * 
     * @return possible object is {@link Mra }
     * 
     */
    public Mra getMra() {
	return mra;
    }

    /**
     * Sets the value of the mra property.
     * 
     * @param value
     *            allowed object is {@link Mra }
     * 
     */
    public void setMra(Mra value) {
	this.mra = value;
    }

    /**
     * Gets the value of the analyticData property.
     * 
     * @return possible object is {@link AnalyticData }
     * 
     */
    public AnalyticData getAnalyticData() {
	return analyticData;
    }

    /**
     * Sets the value of the analyticData property.
     * 
     * @param value
     *            allowed object is {@link AnalyticData }
     * 
     */
    public void setAnalyticData(AnalyticData value) {
	this.analyticData = value;
    }

    /**
     * Gets the value of the coupons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the coupons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCoupons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Coupon }
     * 
     * 
     */
    public List<Coupon> getCoupons() {
	if (coupons == null) {
	    coupons = new ArrayList<Coupon>();
	}
	return this.coupons;
    }

    /**
     * Gets the value of the bookingAgent property.
     * 
     * @return possible object is {@link BookingAgent }
     * 
     */
    public BookingAgent getBookingAgent() {
	return bookingAgent;
    }

    /**
     * Sets the value of the bookingAgent property.
     * 
     * @param value
     *            allowed object is {@link BookingAgent }
     * 
     */
    public void setBookingAgent(BookingAgent value) {
	this.bookingAgent = value;
    }

    /**
     * Gets the value of the travelAdmin property.
     * 
     * @return possible object is {@link TravelAdmin }
     * 
     */
    public TravelAdmin getTravelAdmin() {
	return travelAdmin;
    }

    /**
     * Sets the value of the travelAdmin property.
     * 
     * @param value
     *            allowed object is {@link TravelAdmin }
     * 
     */
    public void setTravelAdmin(TravelAdmin value) {
	this.travelAdmin = value;
    }

    /**
     * Gets the value of the travelAgent property.
     * 
     * @return possible object is {@link TravelAgent }
     * 
     */
    public TravelAgent getTravelAgent() {
	return travelAgent;
    }

    /**
     * Sets the value of the travelAgent property.
     * 
     * @param value
     *            allowed object is {@link TravelAgent }
     * 
     */
    public void setTravelAgent(TravelAgent value) {
	this.travelAgent = value;
    }

    /**
     * Gets the value of the modificationConstraints property.
     * 
     * @return possible object is {@link ModificationConstraints }
     * 
     */
    public ModificationConstraints getModificationConstraints() {
	return modificationConstraints;
    }

    /**
     * Sets the value of the modificationConstraints property.
     * 
     * @param value
     *            allowed object is {@link ModificationConstraints }
     * 
     */
    public void setModificationConstraints(ModificationConstraints value) {
	this.modificationConstraints = value;
    }

    /**
     * Gets the value of the profileDetails property.
     * 
     * @return possible object is {@link ProfileDetails }
     * 
     */
    public ProfileDetails getProfileDetails() {
	return profileDetails;
    }

    /**
     * Sets the value of the profileDetails property.
     * 
     * @param value
     *            allowed object is {@link ProfileDetails }
     * 
     */
    public void setProfileDetails(ProfileDetails value) {
	this.profileDetails = value;
    }

    /**
     * Gets the value of the numberOfAdditionalDriversAllowed property.
     * 
     */
    public int getNumberOfAdditionalDriversAllowed() {
	return numberOfAdditionalDriversAllowed;
    }

    /**
     * Sets the value of the numberOfAdditionalDriversAllowed property.
     * 
     */
    public void setNumberOfAdditionalDriversAllowed(int value) {
	this.numberOfAdditionalDriversAllowed = value;
    }

    /**
     * Gets the value of the additionalDrivers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the additionalDrivers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAdditionalDrivers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalDriver }
     * 
     * 
     */
    public List<AdditionalDriver> getAdditionalDrivers() {
	if (additionalDrivers == null) {
	    additionalDrivers = new ArrayList<AdditionalDriver>();
	}
	return this.additionalDrivers;
    }

    /**
     * Gets the value of the remainingDaysForPickUp property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getRemainingDaysForPickUp() {
	return remainingDaysForPickUp;
    }

    /**
     * Sets the value of the remainingDaysForPickUp property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setRemainingDaysForPickUp(BigInteger value) {
	this.remainingDaysForPickUp = value;
    }

    /**
     * Gets the value of the reservationSubStatus property.
     * 
     * @return possible object is {@link ReservationSubStatus }
     * 
     */
    public ReservationSubStatus getReservationSubStatus() {
	return reservationSubStatus;
    }

    /**
     * Sets the value of the reservationSubStatus property.
     * 
     * @param value
     *            allowed object is {@link ReservationSubStatus }
     * 
     */
    public void setReservationSubStatus(ReservationSubStatus value) {
	this.reservationSubStatus = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationLink }
     * 
     * 
     */
    public List<ReservationLink> getLinks() {
	if (links == null) {
	    links = new ArrayList<ReservationLink>();
	}
	return this.links;
    }

    /**
     * Gets the value of the vriEligible property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getVriEligible() {
	return vriEligible;
    }

    /**
     * Sets the value of the vriEligible property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setVriEligible(Boolean value) {
	this.vriEligible = value;
    }

    /**
     * Gets the value of the onRequestAfterHours property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getOnRequestAfterHours() {
	return onRequestAfterHours;
    }

    /**
     * Sets the value of the onRequestAfterHours property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setOnRequestAfterHours(Boolean value) {
	this.onRequestAfterHours = value;
    }

    /**
     * Gets the value of the oneClickDefaultCarClass property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOneClickDefaultCarClass() {
	return oneClickDefaultCarClass;
    }

    /**
     * Sets the value of the oneClickDefaultCarClass property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOneClickDefaultCarClass(String value) {
	this.oneClickDefaultCarClass = value;
    }

}
