//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//


package com.cts.product.rental.dto.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.cts.product.rental.dto.common.Phone;


/**
 * This holds support phone numbers by booking
 *                 country.
 *             
 * 
 * <p>Java class for SupportContentResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupportContentResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://com.cts.product.rental.dto.messages/}Response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supportPhoneNumbers" type="{http://com.cts.product.rental.dto.common/}Phone" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="prefillUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="joinEplusUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="activateUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nationalReservationUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="alamoReservationUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="printReceiptUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="supportSendMessageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="supportAnswersUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ecForgotPasswordUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="customerSupportUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="faqUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pastTripsUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="profileUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="forgotPasswordUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="forgotUsernameUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="enrollUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="privacyPolicyUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="onlineCheckInUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupportContentResponse", propOrder = {
    "supportPhoneNumbers",
    "prefillUrl",
    "joinEplusUrl",
    "activateUrl",
    "nationalReservationUrl",
    "alamoReservationUrl",
    "printReceiptUrl",
    "supportSendMessageUrl",
    "supportAnswersUrl",
    "ecForgotPasswordUrl",
    "customerSupportUrl",
    "faqUrl",
    "pastTripsUrl",
    "profileUrl",
    "forgotPasswordUrl",
    "forgotUsernameUrl",
    "enrollUrl",
    "privacyPolicyUrl",
    "onlineCheckInUrl"
})
public class SupportContentResponse
    extends Response
    implements Serializable
{

    protected List<Phone> supportPhoneNumbers;
    @XmlElement(required = true)
    protected String prefillUrl;
    @XmlElement(required = true)
    protected String joinEplusUrl;
    @XmlElement(required = true)
    protected String activateUrl;
    @XmlElement(required = true)
    protected String nationalReservationUrl;
    @XmlElement(required = true)
    protected String alamoReservationUrl;
    @XmlElement(required = true)
    protected String printReceiptUrl;
    @XmlElement(required = true)
    protected String supportSendMessageUrl;
    @XmlElement(required = true)
    protected String supportAnswersUrl;
    @XmlElement(required = true)
    protected String ecForgotPasswordUrl;
    @XmlElement(required = true)
    protected String customerSupportUrl;
    @XmlElement(required = true)
    protected String faqUrl;
    @XmlElement(required = true)
    protected String pastTripsUrl;
    @XmlElement(required = true)
    protected String profileUrl;
    @XmlElement(required = true)
    protected String forgotPasswordUrl;
    @XmlElement(required = true)
    protected String forgotUsernameUrl;
    @XmlElement(required = true)
    protected String enrollUrl;
    @XmlElement(required = true)
    protected String privacyPolicyUrl;
    @XmlElement(required = true)
    protected String onlineCheckInUrl;

    /**
     * Gets the value of the supportPhoneNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportPhoneNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportPhoneNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Phone }
     * 
     * 
     */
    public List<Phone> getSupportPhoneNumbers() {
        if (supportPhoneNumbers == null) {
            supportPhoneNumbers = new ArrayList<Phone>();
        }
        return this.supportPhoneNumbers;
    }

    /**
     * Gets the value of the prefillUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefillUrl() {
        return prefillUrl;
    }

    /**
     * Sets the value of the prefillUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefillUrl(String value) {
        this.prefillUrl = value;
    }

    /**
     * Gets the value of the joinEplusUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinEplusUrl() {
        return joinEplusUrl;
    }

    /**
     * Sets the value of the joinEplusUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinEplusUrl(String value) {
        this.joinEplusUrl = value;
    }

    /**
     * Gets the value of the activateUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivateUrl() {
        return activateUrl;
    }

    /**
     * Sets the value of the activateUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivateUrl(String value) {
        this.activateUrl = value;
    }

    /**
     * Gets the value of the nationalReservationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalReservationUrl() {
        return nationalReservationUrl;
    }

    /**
     * Sets the value of the nationalReservationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalReservationUrl(String value) {
        this.nationalReservationUrl = value;
    }

    /**
     * Gets the value of the alamoReservationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlamoReservationUrl() {
        return alamoReservationUrl;
    }

    /**
     * Sets the value of the alamoReservationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlamoReservationUrl(String value) {
        this.alamoReservationUrl = value;
    }

    /**
     * Gets the value of the printReceiptUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintReceiptUrl() {
        return printReceiptUrl;
    }

    /**
     * Sets the value of the printReceiptUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintReceiptUrl(String value) {
        this.printReceiptUrl = value;
    }

    /**
     * Gets the value of the supportSendMessageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportSendMessageUrl() {
        return supportSendMessageUrl;
    }

    /**
     * Sets the value of the supportSendMessageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportSendMessageUrl(String value) {
        this.supportSendMessageUrl = value;
    }

    /**
     * Gets the value of the supportAnswersUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportAnswersUrl() {
        return supportAnswersUrl;
    }

    /**
     * Sets the value of the supportAnswersUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportAnswersUrl(String value) {
        this.supportAnswersUrl = value;
    }

    /**
     * Gets the value of the ecForgotPasswordUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcForgotPasswordUrl() {
        return ecForgotPasswordUrl;
    }

    /**
     * Sets the value of the ecForgotPasswordUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcForgotPasswordUrl(String value) {
        this.ecForgotPasswordUrl = value;
    }

    /**
     * Gets the value of the customerSupportUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerSupportUrl() {
        return customerSupportUrl;
    }

    /**
     * Sets the value of the customerSupportUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerSupportUrl(String value) {
        this.customerSupportUrl = value;
    }

    /**
     * Gets the value of the faqUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaqUrl() {
        return faqUrl;
    }

    /**
     * Sets the value of the faqUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaqUrl(String value) {
        this.faqUrl = value;
    }

    /**
     * Gets the value of the pastTripsUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPastTripsUrl() {
        return pastTripsUrl;
    }

    /**
     * Sets the value of the pastTripsUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPastTripsUrl(String value) {
        this.pastTripsUrl = value;
    }

    /**
     * Gets the value of the profileUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileUrl() {
        return profileUrl;
    }

    /**
     * Sets the value of the profileUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileUrl(String value) {
        this.profileUrl = value;
    }

    /**
     * Gets the value of the forgotPasswordUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForgotPasswordUrl() {
        return forgotPasswordUrl;
    }

    /**
     * Sets the value of the forgotPasswordUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForgotPasswordUrl(String value) {
        this.forgotPasswordUrl = value;
    }

    /**
     * Gets the value of the forgotUsernameUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForgotUsernameUrl() {
        return forgotUsernameUrl;
    }

    /**
     * Sets the value of the forgotUsernameUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForgotUsernameUrl(String value) {
        this.forgotUsernameUrl = value;
    }

    /**
     * Gets the value of the enrollUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollUrl() {
        return enrollUrl;
    }

    /**
     * Sets the value of the enrollUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollUrl(String value) {
        this.enrollUrl = value;
    }

    /**
     * Gets the value of the privacyPolicyUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacyPolicyUrl() {
        return privacyPolicyUrl;
    }

    /**
     * Sets the value of the privacyPolicyUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacyPolicyUrl(String value) {
        this.privacyPolicyUrl = value;
    }

    /**
     * Gets the value of the onlineCheckInUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnlineCheckInUrl() {
        return onlineCheckInUrl;
    }

    /**
     * Sets the value of the onlineCheckInUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnlineCheckInUrl(String value) {
        this.onlineCheckInUrl = value;
    }

}
