//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 04:33:39 PM IST 
//


package com.cts.product.rental.dto.pricing;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.cts.product.rental.dto.common.CurrencyAmount;


/**
 * <p>Java class for Charge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Charge"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="chargeType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="totalPriceView" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="totalPricePayment" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="savingsView" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="savingsPayment" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="maximumRentalAmountView" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="maximumRentalAmountPayment" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="rates" type="{http://com.cts.product.rental.dto.pricing/}Rate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://com.cts.product.rental.dto.pricing/}productCode"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Charge", propOrder = {
    "chargeType",
    "totalPriceView",
    "totalPricePayment",
    "savingsView",
    "savingsPayment",
    "maximumRentalAmountView",
    "maximumRentalAmountPayment",
    "rates",
    "productCode"
})
public class Charge
    implements Serializable
{

    @XmlElement(required = true)
    protected String chargeType;
    @XmlElement(required = true)
    protected CurrencyAmount totalPriceView;
    @XmlElement(required = true)
    protected CurrencyAmount totalPricePayment;
    @XmlElement(required = true)
    protected CurrencyAmount savingsView;
    @XmlElement(required = true)
    protected CurrencyAmount savingsPayment;
    @XmlElement(required = true)
    protected CurrencyAmount maximumRentalAmountView;
    @XmlElement(required = true)
    protected CurrencyAmount maximumRentalAmountPayment;
    protected List<Rate> rates;
    @XmlElement(namespace = "http://com.cts.product.rental.dto.pricing/", required = true)
    protected String productCode;

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the totalPriceView property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getTotalPriceView() {
        return totalPriceView;
    }

    /**
     * Sets the value of the totalPriceView property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setTotalPriceView(CurrencyAmount value) {
        this.totalPriceView = value;
    }

    /**
     * Gets the value of the totalPricePayment property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getTotalPricePayment() {
        return totalPricePayment;
    }

    /**
     * Sets the value of the totalPricePayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setTotalPricePayment(CurrencyAmount value) {
        this.totalPricePayment = value;
    }

    /**
     * Gets the value of the savingsView property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getSavingsView() {
        return savingsView;
    }

    /**
     * Sets the value of the savingsView property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setSavingsView(CurrencyAmount value) {
        this.savingsView = value;
    }

    /**
     * Gets the value of the savingsPayment property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getSavingsPayment() {
        return savingsPayment;
    }

    /**
     * Sets the value of the savingsPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setSavingsPayment(CurrencyAmount value) {
        this.savingsPayment = value;
    }

    /**
     * Gets the value of the maximumRentalAmountView property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getMaximumRentalAmountView() {
        return maximumRentalAmountView;
    }

    /**
     * Sets the value of the maximumRentalAmountView property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setMaximumRentalAmountView(CurrencyAmount value) {
        this.maximumRentalAmountView = value;
    }

    /**
     * Gets the value of the maximumRentalAmountPayment property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getMaximumRentalAmountPayment() {
        return maximumRentalAmountPayment;
    }

    /**
     * Sets the value of the maximumRentalAmountPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setMaximumRentalAmountPayment(CurrencyAmount value) {
        this.maximumRentalAmountPayment = value;
    }

    /**
     * Gets the value of the rates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rate }
     * 
     * 
     */
    public List<Rate> getRates() {
        if (rates == null) {
            rates = new ArrayList<Rate>();
        }
        return this.rates;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

}
