//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.pricing;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtrasContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtrasContent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="equipment" type="{http://com.ehi.gbo.rental.dto.pricing/}EquipmentContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="insurance" type="{http://com.ehi.gbo.rental.dto.pricing/}InsuranceContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ancillary" type="{http://com.ehi.gbo.rental.dto.pricing/}AncillaryContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="fuel" type="{http://com.ehi.gbo.rental.dto.pricing/}FuelContent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtrasContent", propOrder = {
    "equipment",
    "insurance",
    "ancillary",
    "fuel"
})
public class ExtrasContent
    implements Serializable
{

    protected List<EquipmentContent> equipment;
    protected List<InsuranceContent> insurance;
    protected List<AncillaryContent> ancillary;
    protected List<FuelContent> fuel;

    /**
     * Gets the value of the equipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EquipmentContent }
     * 
     * 
     */
    public List<EquipmentContent> getEquipment() {
        if (equipment == null) {
            equipment = new ArrayList<EquipmentContent>();
        }
        return this.equipment;
    }

    /**
     * Gets the value of the insurance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insurance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInsurance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InsuranceContent }
     * 
     * 
     */
    public List<InsuranceContent> getInsurance() {
        if (insurance == null) {
            insurance = new ArrayList<InsuranceContent>();
        }
        return this.insurance;
    }

    /**
     * Gets the value of the ancillary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ancillary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAncillary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AncillaryContent }
     * 
     * 
     */
    public List<AncillaryContent> getAncillary() {
        if (ancillary == null) {
            ancillary = new ArrayList<AncillaryContent>();
        }
        return this.ancillary;
    }

    /**
     * Gets the value of the fuel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fuel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFuel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FuelContent }
     * 
     * 
     */
    public List<FuelContent> getFuel() {
        if (fuel == null) {
            fuel = new ArrayList<FuelContent>();
        }
        return this.fuel;
    }

}
