//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 04:33:39 PM IST 
//


package com.cts.product.rental.dto.pricing;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.cts.product.rental.dto.common.CurrencyAmount;
import com.cts.product.rental.dto.common.enums.PriceDifferenceTypeEnum;


/**
 * <p>Java class for PriceDifference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceDifference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DifferenceType" type="{http://com.cts.product.rental.dto.common.enums/}PriceDifferenceTypeEnum"/&gt;
 *         &lt;element name="DifferenceAmountView" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="DifferenceAmountPayment" type="{http://com.cts.product.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="selectedCarClass" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceDifference", propOrder = {
    "differenceType",
    "differenceAmountView",
    "differenceAmountPayment",
    "selectedCarClass"
})
public class PriceDifference
    implements Serializable
{

    @XmlElement(name = "DifferenceType", required = true)
    @XmlSchemaType(name = "string")
    protected PriceDifferenceTypeEnum differenceType;
    @XmlElement(name = "DifferenceAmountView", required = true)
    protected CurrencyAmount differenceAmountView;
    @XmlElement(name = "DifferenceAmountPayment", required = true)
    protected CurrencyAmount differenceAmountPayment;
    @XmlElement(required = true)
    protected String selectedCarClass;

    /**
     * Gets the value of the differenceType property.
     * 
     * @return
     *     possible object is
     *     {@link PriceDifferenceTypeEnum }
     *     
     */
    public PriceDifferenceTypeEnum getDifferenceType() {
        return differenceType;
    }

    /**
     * Sets the value of the differenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceDifferenceTypeEnum }
     *     
     */
    public void setDifferenceType(PriceDifferenceTypeEnum value) {
        this.differenceType = value;
    }

    /**
     * Gets the value of the differenceAmountView property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getDifferenceAmountView() {
        return differenceAmountView;
    }

    /**
     * Sets the value of the differenceAmountView property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setDifferenceAmountView(CurrencyAmount value) {
        this.differenceAmountView = value;
    }

    /**
     * Gets the value of the differenceAmountPayment property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getDifferenceAmountPayment() {
        return differenceAmountPayment;
    }

    /**
     * Sets the value of the differenceAmountPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setDifferenceAmountPayment(CurrencyAmount value) {
        this.differenceAmountPayment = value;
    }

    /**
     * Gets the value of the selectedCarClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedCarClass() {
        return selectedCarClass;
    }

    /**
     * Sets the value of the selectedCarClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedCarClass(String value) {
        this.selectedCarClass = value;
    }

}
