//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.pricing;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.cts.product.rental.dto.common.CurrencyAmount;


/**
 * <p>Java class for Rate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="unitAmountView" type="{http://com.ehi.gbo.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="unitAmountPayment" type="{http://com.ehi.gbo.rental.dto.common/}CurrencyAmount"/&gt;
 *         &lt;element name="unitRateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="unitRateTypeQuantity" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rate", propOrder = {
    "unitAmountView",
    "unitAmountPayment",
    "unitRateType",
    "unitRateTypeQuantity"
})
public class Rate
    implements Serializable
{

    @XmlElement(required = true)
    protected CurrencyAmount unitAmountView;
    @XmlElement(required = true)
    protected CurrencyAmount unitAmountPayment;
    @XmlElement(required = true)
    protected String unitRateType;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double unitRateTypeQuantity;

    /**
     * Gets the value of the unitAmountView property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getUnitAmountView() {
        return unitAmountView;
    }

    /**
     * Sets the value of the unitAmountView property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setUnitAmountView(CurrencyAmount value) {
        this.unitAmountView = value;
    }

    /**
     * Gets the value of the unitAmountPayment property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmount }
     *     
     */
    public CurrencyAmount getUnitAmountPayment() {
        return unitAmountPayment;
    }

    /**
     * Sets the value of the unitAmountPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmount }
     *     
     */
    public void setUnitAmountPayment(CurrencyAmount value) {
        this.unitAmountPayment = value;
    }

    /**
     * Gets the value of the unitRateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitRateType() {
        return unitRateType;
    }

    /**
     * Sets the value of the unitRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitRateType(String value) {
        this.unitRateType = value;
    }

    /**
     * Gets the value of the unitRateTypeQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUnitRateTypeQuantity() {
        return unitRateTypeQuantity;
    }

    /**
     * Sets the value of the unitRateTypeQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUnitRateTypeQuantity(Double value) {
        this.unitRateTypeQuantity = value;
    }

}
