//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.pricing;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleRate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleRate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="chargeType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="extras" type="{http://com.ehi.gbo.rental.dto.pricing/}ExtrasRates"/&gt;
 *         &lt;element name="priceSummary" type="{http://com.ehi.gbo.rental.dto.pricing/}PriceSummary"/&gt;
 *         &lt;element name="supplemental" type="{http://com.ehi.gbo.rental.dto.pricing/}SupplementalRates"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleRate", propOrder = {
    "chargeType",
    "extras",
    "priceSummary",
    "supplemental"
})
public class VehicleRate
    implements Serializable
{

    @XmlElement(required = true)
    protected String chargeType;
    @XmlElement(required = true)
    protected ExtrasRates extras;
    @XmlElement(required = true)
    protected PriceSummary priceSummary;
    @XmlElement(required = true)
    protected SupplementalRates supplemental;

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the extras property.
     * 
     * @return
     *     possible object is
     *     {@link ExtrasRates }
     *     
     */
    public ExtrasRates getExtras() {
        return extras;
    }

    /**
     * Sets the value of the extras property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtrasRates }
     *     
     */
    public void setExtras(ExtrasRates value) {
        this.extras = value;
    }

    /**
     * Gets the value of the priceSummary property.
     * 
     * @return
     *     possible object is
     *     {@link PriceSummary }
     *     
     */
    public PriceSummary getPriceSummary() {
        return priceSummary;
    }

    /**
     * Sets the value of the priceSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceSummary }
     *     
     */
    public void setPriceSummary(PriceSummary value) {
        this.priceSummary = value;
    }

    /**
     * Gets the value of the supplemental property.
     * 
     * @return
     *     possible object is
     *     {@link SupplementalRates }
     *     
     */
    public SupplementalRates getSupplemental() {
        return supplemental;
    }

    /**
     * Sets the value of the supplemental property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplementalRates }
     *     
     */
    public void setSupplemental(SupplementalRates value) {
        this.supplemental = value;
    }

}
