spring:
   application:
      name: nextgen-ai-service
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp


server:
   port: ${PORT:8080} 
   error:
      include-stacktrace: always
      whitelabel:
         enabled: false
         

logging:
   level:
      org.springframework.web: INFO

      