//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 04:33:39 PM IST 
//


package com.cts.product.rental.dto.common;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mra complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mra"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="unsignedRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="insurancePreferencesOutOfDate" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mra", propOrder = {
    "unsignedRegion",
    "insurancePreferencesOutOfDate"
})
public class Mra
    implements Serializable
{

    @XmlElement(required = true)
    protected String unsignedRegion;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean insurancePreferencesOutOfDate;

    /**
     * Gets the value of the unsignedRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnsignedRegion() {
        return unsignedRegion;
    }

    /**
     * Sets the value of the unsignedRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnsignedRegion(String value) {
        this.unsignedRegion = value;
    }

    /**
     * Gets the value of the insurancePreferencesOutOfDate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInsurancePreferencesOutOfDate() {
        return insurancePreferencesOutOfDate;
    }

    /**
     * Sets the value of the insurancePreferencesOutOfDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsurancePreferencesOutOfDate(Boolean value) {
        this.insurancePreferencesOutOfDate = value;
    }

}
