//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//


package com.cts.product.rental.dto.common;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.cts.product.rental.dto.common.enums.FeeAssignmentType;
import com.cts.product.rental.dto.common.enums.HighestUsedRateType;


/**
 * <p>A RateItem describes all the rates and
 *                 properties associated with a Product / Vehicle. Attributes include
 *                 information about the charge such as rates and type, the currency
 *                 symbol, the category as well as different units of measure such as
 *                 daily, weekly, monthly, maximum and per rental rates. Rates are
 *                 expressed in decimal. Not all attributes in this object are used for
 *                 all items. For example, an item may have a daily, weekly rate but
 *                 does not have a maximum rate, whereas some items may not have a rate
 *                 total. </p>
 *             
 * 
 * <p>Java class for RateItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rateDifference" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateDaily" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateWeekly" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateMaximum" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateTotalDifference" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateCustom" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateCustomUnit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rateDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rateCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rateDifferenceUnit" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rateAssignment" type="{http://com.cts.product.rental.dto.common.enums/}FeeAssignmentType"/&gt;
 *         &lt;element name="allowRateReassign" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="rateHourly" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateMonthly" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="removable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="opaque" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="included" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="chargeUnit" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="chargeBasis" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ratePerRental" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="chargeType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="chargeSequence" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="currencySymbol" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="couponSavingsAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="chargeRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="rateDisplayLine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="highestUsedRate" type="{http://com.cts.product.rental.dto.common.enums/}HighestUsedRateType"/&gt;
 *         &lt;element name="AuxiliaryKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateItem", propOrder = {
    "rateDifference",
    "rateDaily",
    "rateWeekly",
    "rateTotal",
    "rateMaximum",
    "rateTotalDifference",
    "rateCustom",
    "rateCustomUnit",
    "rateDescription",
    "rateCategory",
    "rateDifferenceUnit",
    "rateAssignment",
    "allowRateReassign",
    "rateHourly",
    "rateMonthly",
    "removable",
    "opaque",
    "included",
    "chargeUnit",
    "chargeBasis",
    "ratePerRental",
    "chargeType",
    "chargeSequence",
    "currencySymbol",
    "couponSavingsAmount",
    "chargeRate",
    "rateDisplayLine",
    "highestUsedRate",
    "auxiliaryKey"
})
public class RateItem
    implements Serializable
{

    @XmlElement(required = true)
    protected BigDecimal rateDifference;
    @XmlElement(required = true)
    protected BigDecimal rateDaily;
    @XmlElement(required = true)
    protected BigDecimal rateWeekly;
    @XmlElement(required = true)
    protected BigDecimal rateTotal;
    @XmlElement(required = true)
    protected BigDecimal rateMaximum;
    @XmlElement(required = true)
    protected BigDecimal rateTotalDifference;
    @XmlElement(required = true)
    protected BigDecimal rateCustom;
    @XmlElement(required = true)
    protected String rateCustomUnit;
    @XmlElement(required = true)
    protected String rateDescription;
    @XmlElement(required = true)
    protected String rateCategory;
    @XmlElement(required = true)
    protected String rateDifferenceUnit;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FeeAssignmentType rateAssignment;
    protected boolean allowRateReassign;
    @XmlElement(required = true)
    protected BigDecimal rateHourly;
    @XmlElement(required = true)
    protected BigDecimal rateMonthly;
    protected boolean removable;
    protected boolean opaque;
    protected boolean included;
    protected int chargeUnit;
    @XmlElement(required = true)
    protected BigDecimal chargeBasis;
    @XmlElement(required = true)
    protected BigDecimal ratePerRental;
    @XmlElement(required = true)
    protected String chargeType;
    @XmlElement(required = true)
    protected String chargeSequence;
    @XmlElement(required = true)
    protected String currencySymbol;
    @XmlElement(required = true)
    protected BigDecimal couponSavingsAmount;
    @XmlElement(required = true)
    protected BigDecimal chargeRate;
    @XmlElement(required = true)
    protected String rateDisplayLine;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected HighestUsedRateType highestUsedRate;
    @XmlElement(name = "AuxiliaryKey", required = true)
    protected String auxiliaryKey;

    /**
     * Gets the value of the rateDifference property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateDifference() {
        return rateDifference;
    }

    /**
     * Sets the value of the rateDifference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateDifference(BigDecimal value) {
        this.rateDifference = value;
    }

    /**
     * Gets the value of the rateDaily property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateDaily() {
        return rateDaily;
    }

    /**
     * Sets the value of the rateDaily property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateDaily(BigDecimal value) {
        this.rateDaily = value;
    }

    /**
     * Gets the value of the rateWeekly property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateWeekly() {
        return rateWeekly;
    }

    /**
     * Sets the value of the rateWeekly property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateWeekly(BigDecimal value) {
        this.rateWeekly = value;
    }

    /**
     * Gets the value of the rateTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateTotal() {
        return rateTotal;
    }

    /**
     * Sets the value of the rateTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateTotal(BigDecimal value) {
        this.rateTotal = value;
    }

    /**
     * Gets the value of the rateMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateMaximum() {
        return rateMaximum;
    }

    /**
     * Sets the value of the rateMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateMaximum(BigDecimal value) {
        this.rateMaximum = value;
    }

    /**
     * Gets the value of the rateTotalDifference property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateTotalDifference() {
        return rateTotalDifference;
    }

    /**
     * Sets the value of the rateTotalDifference property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateTotalDifference(BigDecimal value) {
        this.rateTotalDifference = value;
    }

    /**
     * Gets the value of the rateCustom property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateCustom() {
        return rateCustom;
    }

    /**
     * Sets the value of the rateCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateCustom(BigDecimal value) {
        this.rateCustom = value;
    }

    /**
     * Gets the value of the rateCustomUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCustomUnit() {
        return rateCustomUnit;
    }

    /**
     * Sets the value of the rateCustomUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCustomUnit(String value) {
        this.rateCustomUnit = value;
    }

    /**
     * Gets the value of the rateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateDescription() {
        return rateDescription;
    }

    /**
     * Sets the value of the rateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateDescription(String value) {
        this.rateDescription = value;
    }

    /**
     * Gets the value of the rateCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCategory() {
        return rateCategory;
    }

    /**
     * Sets the value of the rateCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCategory(String value) {
        this.rateCategory = value;
    }

    /**
     * Gets the value of the rateDifferenceUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateDifferenceUnit() {
        return rateDifferenceUnit;
    }

    /**
     * Sets the value of the rateDifferenceUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateDifferenceUnit(String value) {
        this.rateDifferenceUnit = value;
    }

    /**
     * Gets the value of the rateAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link FeeAssignmentType }
     *     
     */
    public FeeAssignmentType getRateAssignment() {
        return rateAssignment;
    }

    /**
     * Sets the value of the rateAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeeAssignmentType }
     *     
     */
    public void setRateAssignment(FeeAssignmentType value) {
        this.rateAssignment = value;
    }

    /**
     * Gets the value of the allowRateReassign property.
     * 
     */
    public boolean isAllowRateReassign() {
        return allowRateReassign;
    }

    /**
     * Sets the value of the allowRateReassign property.
     * 
     */
    public void setAllowRateReassign(boolean value) {
        this.allowRateReassign = value;
    }

    /**
     * Gets the value of the rateHourly property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateHourly() {
        return rateHourly;
    }

    /**
     * Sets the value of the rateHourly property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateHourly(BigDecimal value) {
        this.rateHourly = value;
    }

    /**
     * Gets the value of the rateMonthly property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateMonthly() {
        return rateMonthly;
    }

    /**
     * Sets the value of the rateMonthly property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateMonthly(BigDecimal value) {
        this.rateMonthly = value;
    }

    /**
     * Gets the value of the removable property.
     * 
     */
    public boolean isRemovable() {
        return removable;
    }

    /**
     * Sets the value of the removable property.
     * 
     */
    public void setRemovable(boolean value) {
        this.removable = value;
    }

    /**
     * Gets the value of the opaque property.
     * 
     */
    public boolean isOpaque() {
        return opaque;
    }

    /**
     * Sets the value of the opaque property.
     * 
     */
    public void setOpaque(boolean value) {
        this.opaque = value;
    }

    /**
     * Gets the value of the included property.
     * 
     */
    public boolean isIncluded() {
        return included;
    }

    /**
     * Sets the value of the included property.
     * 
     */
    public void setIncluded(boolean value) {
        this.included = value;
    }

    /**
     * Gets the value of the chargeUnit property.
     * 
     */
    public int getChargeUnit() {
        return chargeUnit;
    }

    /**
     * Sets the value of the chargeUnit property.
     * 
     */
    public void setChargeUnit(int value) {
        this.chargeUnit = value;
    }

    /**
     * Gets the value of the chargeBasis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeBasis() {
        return chargeBasis;
    }

    /**
     * Sets the value of the chargeBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeBasis(BigDecimal value) {
        this.chargeBasis = value;
    }

    /**
     * Gets the value of the ratePerRental property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRatePerRental() {
        return ratePerRental;
    }

    /**
     * Sets the value of the ratePerRental property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRatePerRental(BigDecimal value) {
        this.ratePerRental = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the chargeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeSequence() {
        return chargeSequence;
    }

    /**
     * Sets the value of the chargeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeSequence(String value) {
        this.chargeSequence = value;
    }

    /**
     * Gets the value of the currencySymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencySymbol() {
        return currencySymbol;
    }

    /**
     * Sets the value of the currencySymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencySymbol(String value) {
        this.currencySymbol = value;
    }

    /**
     * Gets the value of the couponSavingsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCouponSavingsAmount() {
        return couponSavingsAmount;
    }

    /**
     * Sets the value of the couponSavingsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCouponSavingsAmount(BigDecimal value) {
        this.couponSavingsAmount = value;
    }

    /**
     * Gets the value of the chargeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargeRate() {
        return chargeRate;
    }

    /**
     * Sets the value of the chargeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargeRate(BigDecimal value) {
        this.chargeRate = value;
    }

    /**
     * Gets the value of the rateDisplayLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateDisplayLine() {
        return rateDisplayLine;
    }

    /**
     * Sets the value of the rateDisplayLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateDisplayLine(String value) {
        this.rateDisplayLine = value;
    }

    /**
     * Gets the value of the highestUsedRate property.
     * 
     * @return
     *     possible object is
     *     {@link HighestUsedRateType }
     *     
     */
    public HighestUsedRateType getHighestUsedRate() {
        return highestUsedRate;
    }

    /**
     * Sets the value of the highestUsedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighestUsedRateType }
     *     
     */
    public void setHighestUsedRate(HighestUsedRateType value) {
        this.highestUsedRate = value;
    }

    /**
     * Gets the value of the auxiliaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxiliaryKey() {
        return auxiliaryKey;
    }

    /**
     * Sets the value of the auxiliaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxiliaryKey(String value) {
        this.auxiliaryKey = value;
    }

}
