//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.common;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Email Source Codes on the Subscription endpoint.
 * 
 * <p>Java class for SubscriptionConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionConfig"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="resWithoutLoyaltyUser" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resWithLoyaltyUser" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="enroll" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="standalone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionConfig", propOrder = {
    "resWithoutLoyaltyUser",
    "resWithLoyaltyUser",
    "enroll",
    "standalone"
})
public class SubscriptionConfig
    implements Serializable
{

    @XmlElement(required = true)
    protected String resWithoutLoyaltyUser;
    @XmlElement(required = true)
    protected String resWithLoyaltyUser;
    @XmlElement(required = true)
    protected String enroll;
    @XmlElement(required = true)
    protected String standalone;

    /**
     * Gets the value of the resWithoutLoyaltyUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResWithoutLoyaltyUser() {
        return resWithoutLoyaltyUser;
    }

    /**
     * Sets the value of the resWithoutLoyaltyUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResWithoutLoyaltyUser(String value) {
        this.resWithoutLoyaltyUser = value;
    }

    /**
     * Gets the value of the resWithLoyaltyUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResWithLoyaltyUser() {
        return resWithLoyaltyUser;
    }

    /**
     * Sets the value of the resWithLoyaltyUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResWithLoyaltyUser(String value) {
        this.resWithLoyaltyUser = value;
    }

    /**
     * Gets the value of the enroll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnroll() {
        return enroll;
    }

    /**
     * Sets the value of the enroll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnroll(String value) {
        this.enroll = value;
    }

    /**
     * Gets the value of the standalone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandalone() {
        return standalone;
    }

    /**
     * Sets the value of the standalone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandalone(String value) {
        this.standalone = value;
    }

}
