//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 06:05:25 PM IST 
//


package com.cts.product.rental.dto.reservation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vehicleLogistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vehicleLogistics"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deliveryInfo" type="{http://com.cts.product.rental.dto.reservation/}DeliveryCollectionInfo"/&gt;
 *         &lt;element name="collectionInfo" type="{http://com.cts.product.rental.dto.reservation/}DeliveryCollectionInfo"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vehicleLogistics", propOrder = {
    "deliveryInfo",
    "collectionInfo"
})
public class VehicleLogistics
    implements Serializable
{

    @XmlElement(required = true)
    protected DeliveryCollectionInfo deliveryInfo;
    @XmlElement(required = true)
    protected DeliveryCollectionInfo collectionInfo;

    /**
     * Gets the value of the deliveryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryCollectionInfo }
     *     
     */
    public DeliveryCollectionInfo getDeliveryInfo() {
        return deliveryInfo;
    }

    /**
     * Sets the value of the deliveryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryCollectionInfo }
     *     
     */
    public void setDeliveryInfo(DeliveryCollectionInfo value) {
        this.deliveryInfo = value;
    }

    /**
     * Gets the value of the collectionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryCollectionInfo }
     *     
     */
    public DeliveryCollectionInfo getCollectionInfo() {
        return collectionInfo;
    }

    /**
     * Sets the value of the collectionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryCollectionInfo }
     *     
     */
    public void setCollectionInfo(DeliveryCollectionInfo value) {
        this.collectionInfo = value;
    }

}
