//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.common.enums;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoyaltyProgramType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoyaltyProgramType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INSIDERS"/&gt;
 *     &lt;enumeration value="EMERALDCLUB"/&gt;
 *     &lt;enumeration value="EPLUS"/&gt;
 *     &lt;enumeration value="NON_LOYALTY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LoyaltyProgramType", namespace = "http://com.ehi.gbo.rental.dto.common.enums/")
@XmlEnum
public enum LoyaltyProgramType {

    INSIDERS,
    EMERALDCLUB,
    EPLUS,
    NON_LOYALTY;

    public String value() {
        return name();
    }

    public static LoyaltyProgramType fromValue(String v) {
        return valueOf(v);
    }

}
