//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:12:32 PM IST 
//


package com.cts.product.rental.dto.common.enums;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentBrandType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentBrandType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="VISA"/&gt;
 *     &lt;enumeration value="BUSINESS ACCOUNT-APPLICANT"/&gt;
 *     &lt;enumeration value="MASTERCARD"/&gt;
 *     &lt;enumeration value="AMERICAN EXPRESS"/&gt;
 *     &lt;enumeration value="DISCOVER"/&gt;
 *     &lt;enumeration value="BANKCARD"/&gt;
 *     &lt;enumeration value="EUROCARD"/&gt;
 *     &lt;enumeration value="BANKERS CHECK"/&gt;
 *     &lt;enumeration value="PERSONAL CHECK"/&gt;
 *     &lt;enumeration value="COMPANY CHECK"/&gt;
 *     &lt;enumeration value="TRAVELLERS CHECK"/&gt;
 *     &lt;enumeration value="CASH"/&gt;
 *     &lt;enumeration value="EUROPE INTERNAL"/&gt;
 *     &lt;enumeration value="STATE OF CALIFORNIA CHG"/&gt;
 *     &lt;enumeration value="PH AND H CHARGE CARD"/&gt;
 *     &lt;enumeration value="TILDEN CHARGE CARD"/&gt;
 *     &lt;enumeration value="INTERNAL CENTRAL BILL"/&gt;
 *     &lt;enumeration value="EXTERNAL CB CARDS"/&gt;
 *     &lt;enumeration value="BUSINESS HOUSE PURCHASE ORDER"/&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="INTERNAL ONE TRIP TRAVEL ORDER"/&gt;
 *     &lt;enumeration value="INTERNAL TOUR VOUCHER"/&gt;
 *     &lt;enumeration value="TILDEN ONE TRIP TRAVEL ORDER"/&gt;
 *     &lt;enumeration value="NATL TILDEN TOUR VOUCHER"/&gt;
 *     &lt;enumeration value="EXTERNAL ONE TRIP TRAVEL"/&gt;
 *     &lt;enumeration value="EXTERNAL TOUR VOUCHER"/&gt;
 *     &lt;enumeration value="EXTERNAL EXCHANGE ORDER"/&gt;
 *     &lt;enumeration value="INTERNAL AUSTRALIA VCHR"/&gt;
 *     &lt;enumeration value="INTERNAL EURO VOUCHER"/&gt;
 *     &lt;enumeration value="INTERNAL EXCHANGE ORDER"/&gt;
 *     &lt;enumeration value="EXTERNAL TOUR VOUCHER CANADA"/&gt;
 *     &lt;enumeration value="INSURANCE REPLACMENT"/&gt;
 *     &lt;enumeration value="PREPAID CASH MANIFEST"/&gt;
 *     &lt;enumeration value="EUROCHEQUES"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PaymentBrandType", namespace = "http://com.ehi.gbo.rental.dto.common.enums/")
@XmlEnum
public enum PaymentBrandType {

    VISA("VISA"),
    @XmlEnumValue("BUSINESS ACCOUNT-APPLICANT")
    BUSINESS_ACCOUNT_APPLICANT("BUSINESS ACCOUNT-APPLICANT"),
    MASTERCARD("MASTERCARD"),
    @XmlEnumValue("AMERICAN EXPRESS")
    AMERICAN_EXPRESS("AMERICAN EXPRESS"),
    DISCOVER("DISCOVER"),
    BANKCARD("BANKCARD"),
    EUROCARD("EUROCARD"),
    @XmlEnumValue("BANKERS CHECK")
    BANKERS_CHECK("BANKERS CHECK"),
    @XmlEnumValue("PERSONAL CHECK")
    PERSONAL_CHECK("PERSONAL CHECK"),
    @XmlEnumValue("COMPANY CHECK")
    COMPANY_CHECK("COMPANY CHECK"),
    @XmlEnumValue("TRAVELLERS CHECK")
    TRAVELLERS_CHECK("TRAVELLERS CHECK"),
    CASH("CASH"),
    @XmlEnumValue("EUROPE INTERNAL")
    EUROPE_INTERNAL("EUROPE INTERNAL"),
    @XmlEnumValue("STATE OF CALIFORNIA CHG")
    STATE_OF_CALIFORNIA_CHG("STATE OF CALIFORNIA CHG"),
    @XmlEnumValue("PH AND H CHARGE CARD")
    PH_AND_H_CHARGE_CARD("PH AND H CHARGE CARD"),
    @XmlEnumValue("TILDEN CHARGE CARD")
    TILDEN_CHARGE_CARD("TILDEN CHARGE CARD"),
    @XmlEnumValue("INTERNAL CENTRAL BILL")
    INTERNAL_CENTRAL_BILL("INTERNAL CENTRAL BILL"),
    @XmlEnumValue("EXTERNAL CB CARDS")
    EXTERNAL_CB_CARDS("EXTERNAL CB CARDS"),
    @XmlEnumValue("BUSINESS HOUSE PURCHASE ORDER")
    BUSINESS_HOUSE_PURCHASE_ORDER("BUSINESS HOUSE PURCHASE ORDER"),
    UNKNOWN("UNKNOWN"),
    @XmlEnumValue("INTERNAL ONE TRIP TRAVEL ORDER")
    INTERNAL_ONE_TRIP_TRAVEL_ORDER("INTERNAL ONE TRIP TRAVEL ORDER"),
    @XmlEnumValue("INTERNAL TOUR VOUCHER")
    INTERNAL_TOUR_VOUCHER("INTERNAL TOUR VOUCHER"),
    @XmlEnumValue("TILDEN ONE TRIP TRAVEL ORDER")
    TILDEN_ONE_TRIP_TRAVEL_ORDER("TILDEN ONE TRIP TRAVEL ORDER"),
    @XmlEnumValue("NATL TILDEN TOUR VOUCHER")
    NATL_TILDEN_TOUR_VOUCHER("NATL TILDEN TOUR VOUCHER"),
    @XmlEnumValue("EXTERNAL ONE TRIP TRAVEL")
    EXTERNAL_ONE_TRIP_TRAVEL("EXTERNAL ONE TRIP TRAVEL"),
    @XmlEnumValue("EXTERNAL TOUR VOUCHER")
    EXTERNAL_TOUR_VOUCHER("EXTERNAL TOUR VOUCHER"),
    @XmlEnumValue("EXTERNAL EXCHANGE ORDER")
    EXTERNAL_EXCHANGE_ORDER("EXTERNAL EXCHANGE ORDER"),
    @XmlEnumValue("INTERNAL AUSTRALIA VCHR")
    INTERNAL_AUSTRALIA_VCHR("INTERNAL AUSTRALIA VCHR"),
    @XmlEnumValue("INTERNAL EURO VOUCHER")
    INTERNAL_EURO_VOUCHER("INTERNAL EURO VOUCHER"),
    @XmlEnumValue("INTERNAL EXCHANGE ORDER")
    INTERNAL_EXCHANGE_ORDER("INTERNAL EXCHANGE ORDER"),
    @XmlEnumValue("EXTERNAL TOUR VOUCHER CANADA")
    EXTERNAL_TOUR_VOUCHER_CANADA("EXTERNAL TOUR VOUCHER CANADA"),
    @XmlEnumValue("INSURANCE REPLACMENT")
    INSURANCE_REPLACMENT("INSURANCE REPLACMENT"),
    @XmlEnumValue("PREPAID CASH MANIFEST")
    PREPAID_CASH_MANIFEST("PREPAID CASH MANIFEST"),
    EUROCHEQUES("EUROCHEQUES");
    private final String value;

    PaymentBrandType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentBrandType fromValue(String v) {
        for (PaymentBrandType c: PaymentBrandType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
