//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 07:18:08 PM IST 
//


package com.cts.product.profile.dto.profiles;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Email preference.</p>
 * 
 * <p>Java class for EmailPreference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmailPreference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rentalReceipts" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="specialOffers" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="subscriberPreferencesUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailPreference", propOrder = {
    "rentalReceipts",
    "specialOffers",
    "subscriberPreferencesUrl"
})
public class EmailPreference
    implements Serializable
{

    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean rentalReceipts;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean specialOffers;
    @XmlElement(required = true)
    protected String subscriberPreferencesUrl;

    /**
     * Gets the value of the rentalReceipts property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRentalReceipts() {
        return rentalReceipts;
    }

    /**
     * Sets the value of the rentalReceipts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRentalReceipts(Boolean value) {
        this.rentalReceipts = value;
    }

    /**
     * Gets the value of the specialOffers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSpecialOffers() {
        return specialOffers;
    }

    /**
     * Sets the value of the specialOffers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSpecialOffers(Boolean value) {
        this.specialOffers = value;
    }

    /**
     * Gets the value of the subscriberPreferencesUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberPreferencesUrl() {
        return subscriberPreferencesUrl;
    }

    /**
     * Sets the value of the subscriberPreferencesUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberPreferencesUrl(String value) {
        this.subscriberPreferencesUrl = value;
    }

}
