//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.19 at 07:18:08 PM IST 
//


package com.cts.product.profile.dto.profiles;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Preference.</p>
 * 
 * <p>Java class for Preference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Preference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="emailPreference" type="{http://com.ehi.gbo.profile.dto.profiles/}EmailPreference"/&gt;
 *         &lt;element name="sourceCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="contractSourceCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rentalPreferences" type="{http://com.ehi.gbo.profile.dto.profiles/}ContractualPreferences"/&gt;
 *         &lt;element name="rewardPreferences" type="{http://com.ehi.gbo.profile.dto.profiles/}RewardPreferences"/&gt;
 *         &lt;element name="returnDomainPreferences" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Preference", propOrder = {
    "emailPreference",
    "sourceCode",
    "contractNumber",
    "contractSourceCode",
    "rentalPreferences",
    "rewardPreferences",
    "returnDomainPreferences"
})
public class Preference
    implements Serializable
{

    @XmlElement(required = true)
    protected EmailPreference emailPreference;
    @XmlElement(required = true)
    protected String sourceCode;
    @XmlElement(required = true)
    protected String contractNumber;
    @XmlElement(required = true)
    protected String contractSourceCode;
    @XmlElement(required = true)
    protected ContractualPreferences rentalPreferences;
    @XmlElement(required = true)
    protected RewardPreferences rewardPreferences;
    @XmlElement(required = true, type = Boolean.class, nillable = true)
    protected Boolean returnDomainPreferences;

    /**
     * Gets the value of the emailPreference property.
     * 
     * @return
     *     possible object is
     *     {@link EmailPreference }
     *     
     */
    public EmailPreference getEmailPreference() {
        return emailPreference;
    }

    /**
     * Sets the value of the emailPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailPreference }
     *     
     */
    public void setEmailPreference(EmailPreference value) {
        this.emailPreference = value;
    }

    /**
     * Gets the value of the sourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * Sets the value of the sourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceCode(String value) {
        this.sourceCode = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the contractSourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractSourceCode() {
        return contractSourceCode;
    }

    /**
     * Sets the value of the contractSourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractSourceCode(String value) {
        this.contractSourceCode = value;
    }

    /**
     * Gets the value of the rentalPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link ContractualPreferences }
     *     
     */
    public ContractualPreferences getRentalPreferences() {
        return rentalPreferences;
    }

    /**
     * Sets the value of the rentalPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractualPreferences }
     *     
     */
    public void setRentalPreferences(ContractualPreferences value) {
        this.rentalPreferences = value;
    }

    /**
     * Gets the value of the rewardPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link RewardPreferences }
     *     
     */
    public RewardPreferences getRewardPreferences() {
        return rewardPreferences;
    }

    /**
     * Sets the value of the rewardPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link RewardPreferences }
     *     
     */
    public void setRewardPreferences(RewardPreferences value) {
        this.rewardPreferences = value;
    }

    /**
     * Gets the value of the returnDomainPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getReturnDomainPreferences() {
        return returnDomainPreferences;
    }

    /**
     * Sets the value of the returnDomainPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnDomainPreferences(Boolean value) {
        this.returnDomainPreferences = value;
    }

}
